### PR TITLE
Reduce dock initial size lookups

### LINKED ISSUE #14209: On open, tree-view opens half shown and expands only when mouse action occurs in Atom
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

tree-view opens half shown and expands only when mouse action occurs in Atom
### Steps to Reproduce

1. Open a project in atom with `atom .`

**Expected behavior:** [What you expect to happen]
image

**Actual behavior:** [What actually happens]
image

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions
Atom    : 1.18.0-dev-83efa4b91
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

BETA:
Atom    : 1.17.0-beta1
Electron: 1.3.14
Chrome  : 52.0.2743.82
Node    : 6.5.0

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
gif:
cropped

/cc @nathansobo @matthewwithanm @maxbrunsfeld

### PR DESCRIPTION
**Pull request by matthewwithanm**
Previously, we would get the initial size every time we didn't have an
explicit one. With this commit, we only get the initial size when we
deserialize and when we go from 0 -> 1 pane items.

Also, if the dock doesn't already have an explicit size, we'll use the
preferred size of the item being dragged when peaking the dock. That
way, dropping it won't cause it to change size.

This kinda-but-not-really fixes #14209. The tree view will still report sizes inconsistently but, since we only ask it once, we won't see the symptom.

cc @ungb @nathansobo

### CODE REVIEW

**Comment by maxbrunsfeld** [comment]
✨  This is a really nice change. Do you have time to add some tests for this?

File: src/dock.js [hunk 1]
```diff
@@ -340,13 +351,13 @@ module.exports = class Dock {
...
-    const activePaneItem = this.paneContainer.getActivePaneItem() || this.paneContainer.getPaneItems()[0]
-    if (activePaneItem != null) {
-      initialSize = getPreferredSize(activePaneItem, this.location)
-    }
-    return initialSize == null ? DEFAULT_INITIAL_SIZE : initialSize
+    const activePaneItem = this.paneContainer.getActivePaneItem() || items[0]
+    let initialSize
+    if (activePaneItem) initialSize = getPreferredSize(activePaneItem, this.location)
+    if (initialSize == null && items.length) initialSize = DEFAULT_INITIAL_SIZE
+    return initialSize ? Math.max(MINIMUM_SIZE, initialSize) : null
```
Comment (matthewwithanm) [inline src/dock.js]: I gotta remove this `Math.max()` call. It's gonna be done in `render()` so this is redundant.

Comment (matthewwithanm) [inline src/dock.js]: Don't need the `items.length` check either. If there are items, there'll be an active one.

**Comment by matthewwithanm** [comment]
@maxbrunsfeld 🎉

**Comment by maxbrunsfeld** [comment]
:zap: Nice. Thanks @matthewwithanm!
