### PR TITLE
Ignore autorun on our buffered process commands. Fixes #10082

### LINKED ISSUE #10082: json parsing issues when default code page is changed (Windows 7)
Registry key HKEY_CURRENT_USER\Software\Microsoft\Command Processor\Autorun on my machine is set to "chcp 1251".
Each network query (plugin searh, featured plugins list, etc..) causes an error:
Unexpected token �: ������� ������� ��������: 1251

Whenever I startup my CMD it writes: 
Microsoft Windows [Version 6.1.7601]
(c) Корпорация Майкрософт (Microsoft Corp.), 2009. Все права защищены.
Текущая кодовая страница: 1251

I think that the last line was unexpected somewhere in json porcessor.

You are welcome to ask me any additional info. 

UPD: deleting the key helped me to solve the problem, but it is just a workaround, I really need this key active. 

UPD2: I changed the key to "chcp 1251>NUL". It works fine now.

### PR DESCRIPTION
**Pull request by damieng**
Fixes the problem of apm and atom shell calls via buffered-process being interrupted/confused by autorun entries in the registry by telling our commands to ignore them.

### CODE REVIEW

**Comment by 50Wliu** [comment]
Refs atom/settings-view#162.

File: spec/buffered-process-spec.coffee [hunk 1]
```diff
@@ -2,7 +2,7 @@ ChildProcess = require 'child_process'
 path = require 'path'
 BufferedProcess  = require '../src/buffered-process'
 
-describe "BufferedProcess", ->
+fdescribe "BufferedProcess", ->
```
Comment (lee-dohm) [inline spec/buffered-process-spec.coffee]: :fire: the focus
