### PR TITLE
Correctly autoindent single newline in Selection#insertText

### LINKED ISSUE #11473: Allow autoIndent when inserting single new line `selection.insertText("\n", {autoIndent: true}).
### Prerequisites
* [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#check-if-the-problem-shows-up-in-safe-mode)?
* [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
* [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
* [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
* [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
* [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?

### Description

/cc @kuychaco 

Before v1.7.0 or more specifically before #10878, `selection.insertText("\n", {autoIndent: true})` auto-indented.
The change in this PR added `NonWhitespaceRegExp.test(text)` check, which return `false` for "\n", that result in `autoIndentFirstLine` never be `true`.
Is this intended, necessary change?

I need to autoIndent when inserting single new line in my vim-mode-plus so I have to workaround by manually emulating auto indent when inserting single "\n"
t9md/atom-vim-mode-plus#231

### Steps to Reproduce

in Atom v1.6.0

`selection.insertText("\n", autoIndent: true)` do auto-indent

in Atom v1.7.0
`selection.insertText("\n", autoIndent: true)` don't auto-indent

I want to autoIndend when inserting single new line like it was in v1.6.0.

### PR DESCRIPTION
**Pull request by BinaryMuse**
Fixes #11473

/cc @kuychaco

@t9md I ran vmp specs against this change and they all pass

### CODE REVIEW

File: src/selection.coffee [hunk 1]
```diff
@@ -378,7 +378,7 @@ class Selection extends Model
       indentAdjustment = @editor.indentLevelForLine(precedingText) - options.indentBasis
       @adjustIndent(remainingLines, indentAdjustment)
 
-    if options.autoIndent and NonWhitespaceRegExp.test(text) and not NonWhitespaceRegExp.test(precedingText) and remainingLines.length > 0
+    if options.autoIndent and (text is '\n' or NonWhitespaceRegExp.test(text)) and not NonWhitespaceRegExp.test(precedingText) and remainingLines.length > 0
```
Comment (50Wliu) [inline src/selection.coffee]: Shouldn't this also test for `\r\n` in case of CRLF line endings?

**Comment by BinaryMuse** [comment]
Good catch, @50Wliu, thanks. That conditional was getting gnarly so I split it out as well.
