### PR TITLE
Use spawn instead of execFile and clean up running processes on process exit

### LINKED ISSUE #13084: Shelling out to collect environment variables is creating runaway 100% CPU processes on Linux
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

I'm fairly sure this will end up being an Electron issue, but here goes ...

When I start atom-beta (1.12.0b4, though was present with b3 at least), it spawns a shell ('env') subprocess which burns 100% CPU, attempting to read stdin forever:

```
systemd,1,1 --system --deserialize 126
  ├─atom,15392,10213
  │   ├─atom,15403,10213
  │   │   └─atom,15466,10213
  │   │       ├─zsh,15497,10213 -ilc command env
```

strace on the shell shows this looping forever:

```
rt_sigprocmask(SIG_SETMASK, [], [TSTP TTIN TTOU], 8) = 0
read(0, NULL, 0)                        = 0
rt_sigprocmask(SIG_BLOCK, [TSTP TTIN TTOU], [], 8) = 0
getpgrp()                               = 10213
ioctl(15, TIOCGPGRP, [11445])           = 0
getpgrp()                               = 10213
ioctl(15, TIOCGPGRP, [11445])           = 0
rt_sigprocmask(SIG_SETMASK, [], [TSTP TTIN TTOU], 8) = 0
read(0, NULL, 0)                        = 0
rt_sigprocmask(SIG_BLOCK, [TSTP TTIN TTOU], [], 8) = 0
```

Sometimes this process blocks Atom startup, and you have to kill the shell for Atom's window to show. Sometimes Atom works just fine despite this, and you only realise later when you wonder why your system is slow, and kill the extraneous process. Sometimes closing Atom takes the rogue shell process with it, and sometimes it outlives Atom. Sometimes everything works fine and I can't reproduce it at all.

Either way, safe mode or not has no effect on it, and nothing bright turns up with `--enable-logging`. Timecop shows 'window load time' taking an ungodly amount of time, but with no insight into why.

Happy to supply more details or attempt debugging as needed, with the caveat that I have no idea what I'm doing in JavaScript.
### Steps to Reproduce
1. Have my system
2. Run Atom beta

**Expected behavior:** 'What a nice normal text-editing experience this is'

**Actual behavior:** WOOOOOOOOSSHHHH goes the laptop fan
### Versions

Atom 1.12.0b4 (also occurred with b3)
Fedora 25 (kernel 4.8-rc8+, glibc 2.24, etc)

### PR DESCRIPTION
**Pull request by joefitzgerald**
Fixes #13084

* Listen for the `exit` event on `process`, and kill the child process
* Unregister the event handler once the child process exits
* Switch to use `child_process.spawn` instead of `child_process.execFile` to avoid 100% CPU utilization on linux
* Ensure the environment is always set in `openPaths`

### CODE REVIEW

File: src/update-process-env.js [hunk 1]
```diff
@@ -82,7 +82,7 @@ async function getEnvFromShell (env) {
     if (error.handle) {
       error.handle()
     }
-    console.log('warning: ' + env.SHELL + '-ilc "command env" failed with signal (' + error.signal + ')')
+    console.log('warning: ' + env.SHELL + ' -ic "command env" failed with signal (' + error.signal + ')')
```
Comment (drewmnoel) [inline src/update-process-env.js]: Should be `-lc` instead here

File: src/update-process-env.js [hunk 2]
```diff
@@ -64,7 +64,32 @@ async function getEnvFromShell (env) {
...
+    const buffers = []
+    cp.on('error', (e) => {
+      error = e
+    })
+    cp.stdout.on('data', (data) => {
+      buffers.push(data)
+    })
+    cp.on('close', (code, signal) => {
+      process.removeListener('exit', killer)
+      if (!buffers || !buffers.length) {
```
Comment (thomasjo) [inline src/update-process-env.js]: Surely this can be reduced to
``` js
if (!buffers.length) {
```
since you are explicitly initializing the array a few lines above?

**Comment by as-cii** [comment]
The failing test seems a flaky one, so I'll go ahead and merge this. Thanks, @joefitzgerald!
