### PR TITLE
Make `updateProcessEnv` async and add `core:loaded-shell-environment` activation hook

### LINKED ISSUE #9406: Slow start up time launching from Dock or Mission Control
I noticed that when I launch Atom from my applications that the loading time is significantly longer than if I use the command line.  I'm running a 2014 MacBook Pro.  

I've attached a screen shot of Time Cop showing several packages that have added milliseconds to the load time.  Is there any way to speed up Atom without having to disable packages as I use many of the packages on a regular basis?    

screenshot 2015-11-02 20 06 00

### LINKED ISSUE #13084: Shelling out to collect environment variables is creating runaway 100% CPU processes on Linux
### Prerequisites
- [x] Can you reproduce the problem in [safe mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode)?
- [x] Are you running the [latest version of Atom](http://flight-manual.atom.io/hacking-atom/sections/debugging/#update-to-the-latest-version)?
- [x] Did you check the [debugging guide](http://flight-manual.atom.io/hacking-atom/sections/debugging/)?
- [x] Did you check the [FAQs on Discuss](https://discuss.atom.io/c/faq)?
- [x] Are you reporting to the [correct repository](https://github.com/atom/atom/blob/master/CONTRIBUTING.md#atom-and-packages)?
- [x] Did you [perform a cursory search](https://github.com/issues?q=is%3Aissue+user%3Aatom+-repo%3Aatom%2Felectron) to see if your bug or enhancement is already reported?
### Description

I'm fairly sure this will end up being an Electron issue, but here goes ...

When I start atom-beta (1.12.0b4, though was present with b3 at least), it spawns a shell ('env') subprocess which burns 100% CPU, attempting to read stdin forever:

```
systemd,1,1 --system --deserialize 126
  ├─atom,15392,10213
  │   ├─atom,15403,10213
  │   │   └─atom,15466,10213
  │   │       ├─zsh,15497,10213 -ilc command env
```

strace on the shell shows this looping forever:

```
rt_sigprocmask(SIG_SETMASK, [], [TSTP TTIN TTOU], 8) = 0
read(0, NULL, 0)                        = 0
rt_sigprocmask(SIG_BLOCK, [TSTP TTIN TTOU], [], 8) = 0
getpgrp()                               = 10213
ioctl(15, TIOCGPGRP, [11445])           = 0
getpgrp()                               = 10213
ioctl(15, TIOCGPGRP, [11445])           = 0
rt_sigprocmask(SIG_SETMASK, [], [TSTP TTIN TTOU], 8) = 0
read(0, NULL, 0)                        = 0
rt_sigprocmask(SIG_BLOCK, [TSTP TTIN TTOU], [], 8) = 0
```

Sometimes this process blocks Atom startup, and you have to kill the shell for Atom's window to show. Sometimes Atom works just fine despite this, and you only realise later when you wonder why your system is slow, and kill the extraneous process. Sometimes closing Atom takes the rogue shell process with it, and sometimes it outlives Atom. Sometimes everything works fine and I can't reproduce it at all.

Either way, safe mode or not has no effect on it, and nothing bright turns up with `--enable-logging`. Timecop shows 'window load time' taking an ungodly amount of time, but with no insight into why.

Happy to supply more details or attempt debugging as needed, with the caveat that I have no idea what I'm doing in JavaScript.
### Steps to Reproduce
1. Have my system
2. Run Atom beta

**Expected behavior:** 'What a nice normal text-editing experience this is'

**Actual behavior:** WOOOOOOOOSSHHHH goes the laptop fan
### Versions

Atom 1.12.0b4 (also occurred with b3)
Fedora 25 (kernel 4.8-rc8+, glibc 2.24, etc)

### PR DESCRIPTION
**Pull request by as-cii**
Fixes #9406.
Fixes #13084.

When Atom is launched from the Dock, we invoke the user shell to retrieve environment variables that are assigned by their profile settings. However, we were doing so synchronously during startup, thus causing a [major slowdown](https://github.com/atom/atom/issues/9406) when opening Atom from the Dock and sometimes [hanging the startup process indefinitely](https://github.com/atom/atom/issues/13084).

With this pull request, we are changing `updateProcessEnv` into an asynchronous method. Packages that require shell environment variables to be assigned prior to activation can use the new `core:loaded-shell-environment` activation hook by putting the following snippet in `package.json`:

```json
{"activationHooks": ["core:loaded-shell-environment"]}
```

This will defer packages' activation until `process.env` has been updated with the user environment variables.

/cc: @atom/maintainers

### CODE REVIEW

File: src/update-process-env.js [hunk 1]
```diff
@@ -58,23 +58,25 @@ function shouldGetEnvFromShell (env) {
...
+    childProcess.execFile(env.SHELL, ['-ilc', 'command env'], {encoding: 'utf8', timeout: 5000}, (error, stdout) => {
+      resolve({stdout, error})
+    })
+  })
+
   if (error) {
     if (error.handle) {
       error.handle()
     }
+    console.log('warning: ' + env.SHELL + '-ilc "command env" failed with signal (' + error.signal + ')')
```
Comment (joefitzgerald) [inline src/update-process-env.js]: It is possible that the exit code is non-zero but there is no error.

Comment (joefitzgerald) [inline src/update-process-env.js]: Ahh, got it. Makes sense...

**Comment by ivankravets** [comment]
> Packages that require shell environment variables to be assigned prior to activation can use the new

@as-cii, Could you call this hook when package has been installed via package manager? I've tried to use this hook for @PlatformIO IDE and new release broke installation process. Users need to manually restart Atom and only after it package will be activated.

Thanks!

**Comment by joefitzgerald** [comment]
@ivankravets you point out a key bug in the current implementation: if a user disables a package dependent on this hook for activation, or if a user installs a new package dependent on this hook, or if a user updates a package dependent on this hook, it will fail to activate.

**Comment by ivankravets** [comment]
I made hot fix for PlatformIO IDE that adds this hook ONLY when Atom is >=1.12.2 and ony after install/upgrade procedure. Default IDE's manifest doesn't contain activation hooks. Nevertheless, IDE will add them after first installation.

See https://github.com/platformio/platformio-atom-ide/blob/develop/lib/maintenance.js#L78:L94
