### PR TITLE
Fix folding for lines that contain a comment

### LINKED ISSUE #15308: [Bug] Code folding does not apply consistently to JS files
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Code folding does not apply consistently to JS files

### Steps to Reproduce

1. Edit a JS file
2. execute editor:fold-at-indent-level-1 (ctrl-k ctrl-1)

**Expected behavior:** All functions should be folded (as per previous versions)

**Actual behavior:** Some functions are folded, some are not

**Reproduces how often:** 100%

### Versions
Running Beta to see if this was also an issue in Beta (it is), but first saw this on the current production version.

Atom    : 1.20.0-beta2
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

### Additional Information
Here is some sample code to use (custom JS layout used within an app)

The 2nd function doesn't get folded at all

```
pageOnLoadChecks : function() {
	var AuthorisedUserIDs = new Array('ddfdfd','dfdfdfd');

},

onChangeQuestion_SI_89847 : function(obj) { //handset colour 
	if(a == b){
		c = a;
	}

},
//apply current pricing until change date
pricingChanges : function() {

}
```

### PR DESCRIPTION
**Pull request by as-cii**
Fixes #15308

In attempting to optimize the performance of `isFoldableAtBufferRow` in 3c87b74, we mistakenly introduced a bug that caused lines that contained a comment but didn't start with one to not be foldable anymore.

With this commit we are restoring the previous behavior, thus only disabling folding for lines that start with a comment (ignoring leading whitespaces).

/cc: @nathansobo @Ben3eeE @ungb

### CODE REVIEW

File: src/tokenized-line.coffee [hunk 1]
```diff
@@ -55,6 +55,11 @@ class TokenizedLine
         return @isCommentLine
 
     for tag in @tags
+      # If we haven't encountered any comment scope when reading the first
+      # non-whitespace chunk of text, then we consider this as not being a
+      # comment line.
+      break if tag > 0 and not isWhitespaceOnly(@text.substr(startIndex, tag))
```
Comment (Ben3eeE) [inline src/tokenized-line.coffee]: startIndex is not defined

**Comment by Ben3eeE** [comment]
LGTM :heart:

**Comment by nathansobo** [comment]
⚡️
