### PR TITLE
"Reopen projects" in a new window

### LINKED ISSUE #19149: `File > Reopen Project` adds the project as a folder to the current window on Windows and Linux, doesn't work on macOS
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description
When trying to re-open a project inside Atom with an already open project, then instead of opening a new window with the project, Atom will add the project as project folder to the current project instead (performs "Add Project Folder" instead).

### Steps to Reproduce

1. Open a project
2. File -> Reopen Project -> [Select a project]

**Expected behavior:** Atom opening a new window with the selected project.

**Actual behavior:** Atom adds the selected project as a project folder.

**Reproduces how often:** Always.

### Versions

Atom    : 1.36.0
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3

apm  2.1.3
npm  6.2.0
node 8.9.3 x64
atom 1.36.0
python 3.6.0
git 2.14.1.windows.1
visual studio 2015

OS: Windows 7 Pro x64

*Edit by @rsese to add more version/behavior details*

`File > Reopen Project` on different OSs:

| Operating System     | 1.36.0     | 1.37.0-beta0     |
| :------------- | :------------- | :------------- |
| macOS 10.12.6   | Project Doesn't Reopen | New Window |
| Windows 10     |  Same Window  | Same Window |
| Ubuntu 18.04   |  Same Window  | Same Window |

### Additional Information

This started happening after ugrading to 1.36.0. This did not happen before.

### PR DESCRIPTION
**Pull request by smashwilson**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at https://github.com/atom/atom/tree/master/.github/PULL_REQUEST_TEMPLATE.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see https://flight-manual.atom.io/hacking-atom/sections/writing-specs/.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see https://github.com/atom/atom/tree/master/CONTRIBUTING.md#pull-requests.

### Identify the Bug

Fixes #19149.

### Description of the Change

I'm reworking the IPC messages that `AtomEnvironment` and `AtomApplication` use to communicate messages related to file opening to clarify which are used for what, then making sure that the `application:reopen-projects`, `application:open`, `application:open-file`, and `application:open-folder` use them consistently. I'm also backfilling tests for IPC message handling.

### Alternate Designs

I could have opted for a more surgical fix within the confines of the existing IPC message structure. The way they were structured was fairly confusing though - we had listeners for `"open"`, `"open-command"` with a subcommand switch for `application:open`, `application:open-file`, or `application:open-folder`, and `"open-file"`, all of which behaved in slightly different ways.

I also considered making `application:reopen-projects` pass a `newWindow` parameter to _always_ open a new window for the reopened projects, but opted to preserve the old behavior as closely as I could.

### Possible Drawbacks

Because the `"open"` command handler used by `application:reopen-projects` uses the standard command-line rules for reusing existing windows, there is still a situation which may exhibit undesired behavior:

> Given `[a,b _]`, reopening the project `b` will only refocus the window because the existing window already contains the named path, but that window won't have the same state as the project with `b` alone.

### Verification Process

In addition to unit tests, here's my behavior verification matrix.

Given this directory tree:

```
a/
  1.md
b/
  2.md
```

* 1.36.0 outcome cells marked with :new: have changed from 1.35.1 to 1.36.0 (intentionally or otherwise).
* 1.36.1 outcome cells marked with :new: have intentionally changed from 1.35.1 to 1.36.1.
* 1.36.1 outcome cells marked with :bug: were unintentionally changed from 1.35.1 to 1.36.0 and reverted to their original behavior for 1.36.1.
* 1.36.1 outcome cells marked with :bug: :new: unintentionally changed from 1.35.1 to 1.36.0, but changed to _different_ behavior for 1.36.1.

#### No open windows

| Action | Outcome (<=1.35.1) | Outcome (1.36.0) | Outcome (1.36.1) |
| -- | -- | -- | -- |
| File -> Reopen Project -> a | _(nothing)_ | _(nothing)_ | `[a _]` :bug: :new: |
| File -> Open... -> `a/1.md` | `[a 1.md]` | `[_ 1.md]` :new: | `[_ 1.md]` :new: |

#### One empty window

> `[_ _]`

| Action | Outcome (<=1.35.1) | Outcome (1.36.0) | Outcome (1.36.1) |
| -- | -- | -- | -- |
| File -> Reopen Project -> b | `[b _]` |  `[_ _]` :new: |  `[b _]` :bug: |
| File -> Open... -> `a/1.md` | `[a 1.md]` | `[_ 1.md]` :new: | `[_ 1.md]` :new: |
| File -> Open... -> `a` |  `[a _]` |  `[_ _] [a _]` :new: | `[a _]` :bug: |
| `application:reopen-project`, choose `a` | `[a _]` | `[a _]` | `[a _]` |
| `application:open`, choose `a/1.md` | `[a 1.md]` | `[_ 1.md]` :new: | `[_ 1.md]` :new: |
| `application:open`, choose `b` | `[b _]` | `[_ _] [b _]` | `[b _]` :bug: |
| `application:open-file`, choose `a/1.md` | `[a 1.md]` | `[_ 1.md]` :new: | `[_ 1.md]` :bug: :new: |
| `application:open-folder`, choose `b` | `[b _]` | `[_ _] [b _]` :new: | `[b _]` :bug: :new: |

#### One window with a project root

> `[a _]`

| Action | Outcome (<=1.35.1) | Outcome (1.36.0) | Outcome (1.36.1) |
| -- | -- | -- | -- |
| File -> Reopen Project -> `b` | `[a _] [b _]` | `[a _]` :new: | `[a _] [b _]` :bug: |
| File -> Open... -> `a/1.md` | `[a 1.md]` | `[a 1.md]` | `[a 1.md]` |
| File -> Open... -> `b/2.md` | `[a 2.md]` | `[a 2.md]` | `[a 2.md]` |
| File -> Open... -> `b` | `[a _] [b _]` | `[a _] [b _]` | `[a _] [b _]` |
| `application:reopen-project`, choose `b` | `[a _] [b _]` | `[a,b _]` :new: | `[a _] [b _]` :bug: |
| `application:open`, choose `b/2.md` | `[a 2.md]` | `[a 2.md]` | `[a 2.md]` |
| `application:open`, choose `b` | `[a _] [b _]` | `[a _] [b _]` | `[a _] [b _]` |
| `application:open-file`, choose `a/1.md` | `[a 1.md]` | `[a 1.md]` | `[a 1.md]` |
| `application:open-file`, choose `b/2.md` | `[a 2.md]` | `[a 2.md]` | `[a 2.md]` |
| `application:open-folder`, choose `b` | `[a _] [b _]` | `[a _] [b _]` | `[a _] [b _]` |

#### That weird edge case

> `[a,b _]`<br/>
> `b` has project state of `2.md`

| Action | Outcome (<=1.35.1) | Outcome (1.36.0) | Outcome (1.36.1) |
| -- | -- | -- | -- |
| File -> Reopen Project -> `b` | `[a _] [b _]` | `[a _] [b _]` | `[a _] [b _]` |

### Release Notes

* "File -> Reopen Project" works correctly on macOS when no windows are open.
* "File -> Reopen Project" from the application menu opens the chosen project folders.
* Choosing `application:reopen-project` from the command palette opens chosen project folders in a new window when appropriate.

The other :new: and :bug: :new: rows correspond to changes introduced by #19169.

### CODE REVIEW

File: src/main-process/atom-application.js [hunk 1]
```diff
@@ -590,6 +597,9 @@ class AtomApplication extends EventEmitter {
       this.deleteSocketSecretFile()
     }))
 
+    // Triggered by the 'open-file' event from Electron:
+    // https://electronjs.org/docs/api/app#event-open-file-macos
+    // For example, this is fired when a file is dragged and dropped onto the dock.
```
Comment (jasonrudolph) [inline src/main-process/atom-application.js]: Would the following change be an accurate clarification?

```suggestion
    // For example, this is fired when a file is dragged and dropped onto the Atom application icon in the dock.
```

**Review by jasonrudolph — APPROVED** [review]
> In addition to unit tests, here's my behavior verification matrix.

Thanks for writing this up! 😍 As a reviewer, I found this matrix super helpful in getting up to speed on the behavioral changes provided by this pull request.

I reviewed the code, and it matches my expectations for how we want things to behave.

I also built this branch locally and manually tested a handful of scenarios, and all of them behaved as advertised. 

⚡👍🚀
