### PR TITLE
Throw an exception when adding a non-object pane item

### LINKED ISSUE #5978: Uncaught TypeError: Invalid value used as weak map key
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Invalid value used as weak map key

```
At /Applications/Atom.app/Contents/Resources/app/src/view-registry.js:53

TypeError: Invalid value used as weak map key
  at WeakMap.get (native)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:56:29)
  at atom-pane.PaneElement.activeItemChanged (/Applications/Atom.app/Contents/Resources/app/src/pane-element.js:108:29)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:264:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:328:21)
  at Pane.module.exports.Pane.activateItemAtIndex (/Applications/Atom.app/Contents/Resources/app/src/pane.js:322:19)
  at Pane.module.exports.Pane.activateNextItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:283:21)
  at Pane.module.exports.Pane.removeItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:391:16)
  at Pane.module.exports.Pane.destroyItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:457:16)
  at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:436:12)
  at Workspace.module.exports.Workspace.destroyActivePaneItem (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:697:35)
  at Workspace.module.exports.Workspace.destroyActivePaneItemOrEmptyPane (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:741:21)
  at atom-workspace.atom.commands.add.core:close (/Applications/Atom.app/Contents/Resources/app/src/workspace-element.js:292:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:246:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```

### Commands

```
     -0:15.8 core:cut (atom-text-editor.editor.is-focused)
     -0:15.5 editor:delete-line (atom-text-editor.editor.is-focused)
  4x -0:14.9 core:move-up (atom-text-editor.editor.is-focused)
     -0:13.6 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:13.4 editor:newline (atom-text-editor.editor.is-focused)
     -0:13.2 core:paste (atom-text-editor.editor.is-focused)
  2x -0:11.8 core:move-up (atom-text-editor.editor.is-focused)
     -0:11.4 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  8x -0:10.9 core:select-right (atom-text-editor.editor.is-focused)
  5x -0:07.9 core:save (atom-text-editor.editor.is-focused)
     -0:05.8 core:move-right (atom-text-editor.editor.is-focused)
     -0:05.6 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:03.6 core:save (atom-text-editor.editor.is-focused)
     -0:02.8 beautify:beautify-editor (atom-text-editor.editor.is-focused)
  4x -0:02.1 core:save (atom-text-editor.editor.is-focused)
     -0:00.9 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "editor": {
    "invisibles": {},
    "fontSize": 14
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.22.2
external-open, v0.5.1
git-plus, v4.4.8
javascript-snippets, v1.0.0
language-javascript, v0.63.0
minimap, v4.6.0
node-resolver, v1.0.1

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by nathansobo**
Closes #5978

We end up attempting to retrieve a view for pane items from a WeakMap, which can only use objects as keys. Throwing an exception earlier helps to clarify to package authors that this won't work.

### CODE REVIEW

File: src/pane.coffee [hunk 1]
```diff
@@ -336,6 +336,8 @@ class Pane extends Model
   #
   # Returns the added item.
   addItem: (item, index=@getActiveItemIndex() + 1) ->
+    throw new Error("Added a null item") unless item? and typeof item is 'object'
```
Comment (kevinsawicki) [inline src/pane.coffee]: The error message seems a bit confusing since it isn't always a null item, it also throws for numbers and strings right?

Comment (nathansobo) [inline src/pane.coffee]: You're right. Oversight. I expanded to non-objects and forgot to update the message.
