### PR TITLE
Better errors

### LINKED ISSUE #97: Uncaught TypeError: Unable to watch path
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.169.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [snippets](https://github.com/atom/snippets) package, v0.66.0

### Stack Trace

Uncaught TypeError: Unable to watch path

```
At /usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66

TypeError: Unable to watch path
  at TypeError (native)
  at HandleWatcher.start (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:66:29)
  at new HandleWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:30:12)
  at new PathWatcher (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:120:30)
  at Object.exports.watch (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/main.js:179:12)
  at File.module.exports.File.subscribeToNativeChangeEvents (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:364:109)
  at File.module.exports.File.willAddSubscription (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:101:14)
  at /usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:3:61
  at File.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at File.module.exports.Emitter.on (/usr/share/atom/resources/app/node_modules/emissary/lib/emitter.js:48:14)
  at File.module.exports.File.on (/usr/share/atom/resources/app/node_modules/pathwatcher/lib/file.js:76:40)
  at /usr/share/atom/resources/app/node_modules/snippets/lib/snippets.js:166:30
  at Object.oncomplete (fs.js:93:15)
  at Ipc.sendSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:39:29)
  at BrowserWindow.RemoteMemberFunction [as setSize] (/usr/share/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:69:19)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
No installed packages

# Dev
No dev packages
```

/cc @atom/core

### LINKED ISSUE #4421: Uncaught Error: Atom can only handle files < 2MB for now.
Uncaught Error: Atom can only handle files < 2MB for now.

**Atom Version**: 0.153.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [tree-view](https://github.com/atom/tree-view) package

### LINKED ISSUE #4576: Uncaught Error: ENOENT, open 'login_spec.rb'
Uncaught Error: ENOENT, open '/Users/artur/Web/3mundi/guest/spec/requests/login_spec.rb'

**Atom Version**: 0.155.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: ENOENT, open '/Users/artur/Web/3mundi/guest/spec/requests/login_spec.rb'
  at Error (native)

```

### LINKED ISSUE #4639: when changing branch and currently open file doesn't exist in the moving branch
Uncaught Error: ENOENT, open '/Users/artur/Web/3mundi/guest/spec/controllers/admin/searches_controller_spec.rb'

**Atom Version**: 0.158.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: ENOENT, open '/Users/artur/Web/3mundi/guest/spec/controllers/admin/searches_controller_spec.rb'
  at Error (native)

```

### LINKED ISSUE #4751: Uncaught Error: ENOENT, open '/Users/artur/Web/3mundi/guest/app/views/layouts/_navbar.html.haml'
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.9.5
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open '/Users/artur/Web/3mundi/guest/app/views/layouts/_navbar.html.haml'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: ENOENT, open '/Users/artur/Web/3mundi/guest/app/views/layouts/_navbar.html.haml'
  at Error (native)

```

### Commands

```
     -6:12.6 core:move-left (input.hidden-input)
  4x -6:12.2 editor:move-to-beginning-of-word (input.hidden-input)
     -6:11.1 core:move-left (input.hidden-input)
     -6:09.3 core:backspace (input.hidden-input)
     -6:06.4 editor:newline (input.hidden-input)
     -6:05.6 core:undo (input.hidden-input)
     -6:04.9 core:backspace (input.hidden-input)
     -6:02.5 editor:move-to-end-of-screen-line (input.hidden-input)
  7x -5:57.4 core:undo (input.hidden-input)
     -5:54.9 core:save (input.hidden-input)
     -3:54.9 core:move-right (input.hidden-input)
     -3:32.9 ruby-test:test-single (input.hidden-input)
     -1:32.4 core:backspace (input.hidden-input)
     -1:31.0 core:save (input.hidden-input)
  5x -0:03.1 core:backspace (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "seti-ui",
      "no-caffeine-syntax"
    ],
    "disabledPackages": [
      "tree-view",
      "tabs",
      "linter-jshint",
      "symbols-view",
      "snippets",
      "task-list",
      "linter-rubocop"
    ],
    "projectHome": "/Users/artur/web"
  },
  "editor": {
    "showIndentGuide": true,
    "showInvisibles": true,
    "fontSize": 19
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.17.0
atom-ctags, v2.4.1
autocomplete-paths, v0.7.0
autocomplete-plus, v0.21.0
autocomplete-snippets, v0.2.0
coffee-lint, v0.7.3
color-picker, v1.2.5
highlight-selected, v0.6.2
html2haml, v0.3.0
language-haml, v0.10.0
linter, v0.7.3
linter-csslint, v0.0.11
linter-erb, v0.0.3
linter-ruby, v0.1.4
linter-shellcheck, v0.0.6
minimap, v3.3.8
no-caffeine-syntax, v0.6.0
ruby-slim, v0.2.0
ruby-test, v0.9.1
seti-ui, v0.3.6
sublime-tabs, v0.4.7
trailing-spaces, v0.2.3

# Dev
No dev packages
```

### LINKED ISSUE #4850: Uncaught Error: ENOENT, open '/Users/joscha/Development/mailbutler/node_modules/grunt-crx/tasks/crx.js'
1. switch the node_modules package from a version to a git repository
2. npm install

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: Atom Core

### Stack Trace

Uncaught Error: ENOENT, open '/Users/joscha/Development/mailbutler/node_modules/grunt-crx/tasks/crx.js'

```
At /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:126

Error: ENOENT, open '/Users/joscha/Development/mailbutler/node_modules/grunt-crx/tasks/crx.js'
  at Error (native)

```

### Commands

```
     -0:28.1 find-and-replace:show (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:26.0 core:confirm (input.hidden-input)
  7x -0:19.3 core:move-left (input.hidden-input)
     -0:14.9 core:backspace (input.hidden-input)
     -0:14.2 core:move-left (input.hidden-input)
  2x -0:13.7 core:move-right (input.hidden-input)
     -0:13.1 core:move-left (input.hidden-input)
     -0:12.8 core:backspace (input.hidden-input)
  7x -0:12.5 core:move-right (input.hidden-input)
     -0:11.3 core:backspace (input.hidden-input)
  2x -0:10.9 core:move-right (input.hidden-input)
     -0:09.7 core:backspace (input.hidden-input)
  5x -0:09.3 core:move-left (input.hidden-input)
     -0:02.6 core:copy (input.hidden-input)
     -0:00.7 core:paste (input.hidden-input)
     -0:00.0 core:save (input.hidden-input)
```

### Config

```
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ]
  },
  "editor": {
    "showInvisibles": true,
    "autoIndentOnPaste": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jasmine, v0.4.0
editorconfig, v0.2.2
jsformat, v0.7.18
language-scala, v1.1.0
linter, v0.9.0
linter-coffeelint, v0.1.7
linter-jshint, v0.1.0
linter-php, v0.0.11
travis-ci-status, v0.11.1
visual-bell, v0.9.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by benogle**
- When someone does not have access, opens a large file, or opens a bad file, it will have a nice error.
  screen shot 2015-01-08 at 5 18 45 pm
  - Closes #4421 
- When there is an error reading the file after getting a file changed event, it will have a better error. 
  screen shot 2015-01-08 at 5 12 52 pm
  - Relies on https://github.com/atom/text-buffer/pull/41 and https://github.com/atom/node-pathwatcher/pull/54
  - Closes #4850 
  - Closes #4751 
  - Closes #4639 
  - Closes #4576 
- When there is a problem opening / watching config, keymaps, snippets, we display a better error.
  - Closes atom/snippets#97
### TODO
- [x] Open access errors
- [x] Errors on read after file change event
- [x] `unable to watch path` errors for config, keymap, user scripts on startup
- [x] Make sure the bad-config errors arent crazy

### CODE REVIEW

**Comment by kevinsawicki** [comment]
Love this :+1:

**Comment by benogle** [comment]
There are so many places we throw sketch app-killing errors.

File: src/project.coffee [hunk 1]
```diff
@@ -282,7 +287,9 @@ class Project extends Model
   # Returns a promise that resolves to the {TextBuffer}.
   buildBuffer: (absoluteFilePath) ->
     if fs.getSizeSync(absoluteFilePath) >= 2 * 1048576 # 2MB
-      throw new Error("Atom can only handle files < 2MB for now.")
+      error = new Error("Atom can only handle files < 2MB for now.")
+      error.name = 'OversizeFileError'
```
Comment (kevinsawicki) [inline src/project.coffee]: What do you think about just using a custom `code` instead? To be consistent with other IO errors from node.

This could be be like `error.code = 'ETOOLARGETOOPEN` or something.

File: src/workspace.coffee [hunk 2]
```diff
@@ -446,7 +446,19 @@ class Workspace extends Model
     if uri?
       item = pane.itemForUri(uri)
       item ?= opener(atom.project.resolve(uri), options) for opener in @getOpeners() when !item
-    item ?= atom.project.open(uri, options)
+
+    try
+      item ?= atom.project.open(uri, options)
+    catch error
+      if error.code is 'EFILETOOLARGE'
+        atom.notifications.addWarning(error.message + " Large file support is being tracked at [atom/atom#307](https://github.com/atom/atom/issues/307).")
```
Comment (kevinsawicki) [inline src/workspace.coffee]: :lipstick: `"#{error.message} Large file support..."`

Comment (benogle) [inline src/workspace.coffee]: obv

File: src/config.coffee [hunk 3]
```diff
@@ -832,25 +832,29 @@ class Config
       @configFileHasErrors = false
     catch error
       @configFileHasErrors = true
-      @notifyFailure('Failed to load config.cson', error)
+      if error.location?
+        @notifyFailure('Failed to load config.cson', error.stack)
```
Comment (kevinsawicki) [inline src/config.coffee]: This might be `config.json` so you may want to use `path.basename(@getUserConfigPath())`

File: src/config.coffee [hunk 4]
```diff
@@ -832,25 +832,29 @@ class Config
...
+        @notifyFailure('Failed to load config.cson', error.message)
 
   observeUserConfig: ->
     try
       @watchSubscription ?= pathWatcher.watch @configFilePath, (eventType) =>
         @debouncedLoad() if eventType is 'change' and @watchSubscription?
     catch error
-      @notifyFailure('Failed to watch user config', error)
+      @notifyFailure """
+        Unable to watch path: `config.cson`. Make sure you have permissions to
```
Comment (kevinsawicki) [inline src/config.coffee]: Same here, `config.json` is possible.

File: src/keymap-extensions.coffee [hunk 5]
```diff
@@ -20,12 +20,27 @@ KeymapManager::getUserKeymapPath = ->
...
   userKeymapPath = @getUserKeymapPath()
-  if fs.isFileSync(userKeymapPath)
+  return unless fs.isFileSync(userKeymapPath)
+
+  try
     @loadKeymap(userKeymapPath, watch: true, suppressErrors: true)
+  catch error
+    if error.message.indexOf('Unable to watch path') > -1
+      message = """
+        Unable to watch path: `keymap.cson`. Make sure you have permissions to
```
Comment (kevinsawicki) [inline src/keymap-extensions.coffee]: Same thing here, I think this could be `keymap.json` as well.

Comment (benogle) [inline src/keymap-extensions.coffee]: yeah, it's on the list

**Comment by benogle** [comment]
Ok, I think this is ready to go. @kevinsawicki another quick pass would be rad

**Comment by kevinsawicki** [comment]
Just a heads up, you might want to rebase, doesn't look like this will merge cleanly currently.

File: src/keymap-extensions.coffee [hunk 6]
```diff
@@ -20,12 +20,37 @@ KeymapManager::getUserKeymapPath = ->
...
+      atom.notifications.addError(message, {dismissable: true})
+    else
+      detail = error.path
+      stack = error.stack
+      atom.notifications.addFatalError(error.message, {detail, stack, dismissable: true})
 
 KeymapManager::subscribeToFileReadFailure = ->
-  this.onDidFailToReadFile (error) ->
-    atom.notifications.addError('Failed to load keymap.cson', {detail: error.stack, dismissable: true})
+  this.onDidFailToReadFile (error) =>
```
Comment (kevinsawicki) [inline src/keymap-extensions.coffee]: `@` instead of `this`? I see it was using `this` before, but might be nice to change it now since it is being edited.

File: src/project.coffee [hunk 7]
```diff
@@ -323,6 +332,17 @@ class Project extends Model
     else
       @on 'buffer-created', (buffer) -> callback(buffer)
 
+  subscribeToBuffer: (buffer) ->
+    buffer.onDidDestroy => @removeBuffer(buffer)
+    buffer.onWillThrowWatchError ({error, handle}) =>
+      handle()
+      atom.notifications.addWarning """
+        Unable to read file after file `#{error.eventType}` event.
+        Make sure you have permission to access `#{@getPath()}`.
```
Comment (kevinsawicki) [inline src/project.coffee]: I think `@getPath()` is deprecated right?

File: spec/workspace-view-spec.coffee [hunk 8]
```diff
@@ -295,39 +295,3 @@ describe "WorkspaceView", ->
 
       modalContainer = workspaceElement.querySelector('atom-panel-container.modal')
       expect(modalContainer.parentNode).toBe workspaceElement
-
-  describe "::saveActivePaneItem()", ->
-    describe "when there is an error", ->
-      it "emits a warning notification when the file cannot be saved", ->
-        spyOn(Pane::, 'saveActiveItem').andCallFake ->
```
Comment (kevinsawicki) [inline spec/workspace-view-spec.coffee]: Super minor, but I wonder if the `Pane` require can be removed from this file now.

File: src/project.coffee (hunk 7 above)
Comment (benogle) [inline src/project.coffee]: Should be `buffer.getPath()` :flushed:
