### PR TITLE
Clear dimensions cache when approximate screen line count changes

### LINKED ISSUE #15761: Atom editor renders random text over each other.
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

Atom editor renders random text over each other.

I am currently unable to get repro steps for this but have screenshots of the scenario

**Expected behavior:** [What you expect to happen]
Text should show up and other lines shouldn't be rendered on top

**Actual behavior:** [What actually happens]
Additional random lines are rendered above current lines and don't disappear after scrolling.
image

image

**Reproduces how often:** [What percentage of the time does it reproduce?]
I can't repro this again and unsure what I did to get to this scenario

### Versions

```
Atom    : 1.22.0-dev-1880e1401
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

```

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

While scrolling you can see it updates the line numbers but there's additional lines that just stay there.
scrolling

/CC @nathansobo @as-cii

### PR DESCRIPTION
**Pull request by as-cii**
Fixes #15761

It is possible for the approximate screen line count to exceed the actual number of lines. This may happen if there are many soft-wraps and the display layer hasn't indexed the entire contents of the buffer. 

In that circumstance, if a user attempts to scroll to a position that does not exist, we are unable to clip it correctly in `setScrollTop` because the line count approximation is also wrong. Therefore, after populating the spatial index in `updateSyncBeforeMeasuringContent`, we will make sure that the approximate screen line count did not change. If it did, we need to clear the derived dimensions cache (which contains, for example, the rendered row range) because it could contain incorrect values.

/cc: @nathansobo @Ben3eeE @ungb @rsese

### CODE REVIEW

File: spec/text-editor-component-spec.js [hunk 1]
```diff
@@ -894,6 +896,73 @@ describe('TextEditorComponent', () => {
...
+      beforeEach(() => {
+        originalTimeout = jasmine.getEnv().defaultTimeoutInterval
+        jasmine.getEnv().defaultTimeoutInterval = 60 * 1000
+      })
+
+      afterEach(() => {
+        jasmine.getEnv().defaultTimeoutInterval = originalTimeout
+      })
+
+      it('renders the visible rows correctly after randomly mutating the editor', async () => {
```
Comment (nathansobo) [inline spec/text-editor-component-spec.js]: Thanks so much for adding this. We probably should have had something like this all along. Lesson learned. We should never again release a system this complex without randomized testing it.

File: src/text-editor-component.js [hunk 2]
```diff
@@ -2884,10 +2884,25 @@ class TextEditorComponent {
...
-    const visibleTileCount = Math.ceil(editorHeightInTiles) + 1
-    const lastRenderedRow = renderedStartRow + (visibleTileCount * this.getRowsPerTile())
-    this.props.model.displayLayer.populateSpatialIndexIfNeeded(Infinity, lastRenderedRow)
+    const {model} = this.props
+    const previousScreenLineCount = model.getApproximateScreenLineCount()
+
+    const renderedEndRow = renderedStartRow + (this.getVisibleTileCount() * this.getRowsPerTile())
+    this.props.model.displayLayer.populateSpatialIndexIfNeeded(Infinity, renderedEndRow)
+
+    // It is possible for the approximate screen line count to exceed the actual
```
Comment (nathansobo) [inline src/text-editor-component.js]: The first sentence of this comment is confusing to me. Isn't the problem that the approximate screen line count is actually *less* than the actual screen line count because it's not accounting for all the soft wraps? I wonder if we should just always clear the dimensions cache when going down this code path for simplicity.

**Comment by maxbrunsfeld** [comment]
👏
