### PR TITLE
Check if files are accessible during deserialization

### LINKED ISSUE #4199: Bug when starting editor under certain conditions
When I closed the editor I had a file open in a tab. It was named "summarize". 
With the editor closed I ended up having to do some restructuring of the project folder and this file was moved into a directory called "summarize" under a different name.
Later in the day I tried to start up Atom again, it failed to the debug screen. It was throwing an error saying that this file was now a directory. I ended up having to rename the directory temporarily to be able to open the editor, then close the tab in the editor, rename the directory again to it's original name and all was well.
Suggestion: the editor should fail more gracefully in this circumstance. When a directory replaces a file of the same name, the editor should just close the tab or gray it out with an explanation or alert.

### LINKED ISSUE #4939: Do not deserialize files that do not exist or we do not have permission to
Steps to reproduce

1. Open file1 in atom
1. Open file2 in atom
1. Close atom
1. Remove file1
1. `chmod 000 file2`
1. Open atom to the dir of file2
1. Broken

these 2 cases should be fixed

* When the file doesnt exist anymore, an empty tab is created
* When the user does not have permissions, it fails hard with a big scary `unable to watch path` stack trace

### LINKED ISSUE #5084: Can't open a directory called specs
i'm not sure what's going on here. it only happens on this directory, but if i make another directory called specs, atom opens.

i open atom by going to the folder in the terminal and typing `atom` or `atom .`.

screen shot 2015-01-15 at 11 13 51 am

what else do you guys need?

### PR DESCRIPTION
**Pull request by kevinsawicki**
If a buffer's serialized path was a directory upon deserialization then Atom would previously fail to launch.

Now these invalid buffers are ignored and deserialization can complete successfully.

Fixes #4199
Fixes #4939
Fixes #5084

### CODE REVIEW

**Comment by benogle** [comment]
The same problem occurs when the user does not have permission to read a file on deserialize. I was going to make it not open the problematic buffer.

**Comment by kevinsawicki** [comment]
> The same problem occurs when the user does not have permission to read a file on deserialize. 

It blows up and prevents deserialization? Or just shows a notification? Just curious, this looked like the only uncaught error thrown by `new File`

**Comment by benogle** [comment]
> It blows up and prevents deserialization?

This. Open file, close atom, chmod 000 file.js, open atom, does not start.

**Comment by kevinsawicki** [comment]
> This. Open file, close atom, chmod 000 file.js, open atom, does not start.

Indeed, will address here.

**Comment by benogle** [comment]
I made an issue for it a bit ago: https://github.com/atom/atom/issues/4939

**Comment by kevinsawicki** [comment]
> I made an issue for it a bit ago: #4939

Okay, updated it to check if the file is accessible during deserialization.

File: spec/project-spec.coffee [hunk 1]
```diff
@@ -37,6 +37,32 @@ describe "Project", ->
...
+    it "does not deserialize buffers when their path is inaccessible", ->
+      pathToOpen = path.join(temp.mkdirSync(), 'file.txt')
+      fs.writeFileSync(pathToOpen, '')
+
+      waitsForPromise ->
+        atom.project.open(pathToOpen)
+
+      runs ->
+        expect(atom.project.getBuffers().length).toBe 1
+        fs.chmodSync(pathToOpen, '000')
```
Comment (benogle) [inline spec/project-spec.coffee]: Can the system delete this file now?

Comment (kevinsawicki) [inline spec/project-spec.coffee]: `fs.removeSync` still works on it
