### PR TITLE
Move highlight decorations outside of tiles

### LINKED ISSUE #15449: Recreated highlight node re-trigger keyframe animation on contained line-tile changed
CC @nathansobo, @as-cii

Similar to #15185 except
- This issue happens even in v1.18.0(before editor rewrite).
- Different condition than #15185.

decoration-node-recreated

I understand fixing this is not easy but hope fixed.
Thanks for great work as always.

### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When highlight node is **moved** to different lines-tile, highlight node on existing lines-tile re-created and re-trigger keyframe animation.

### Steps to Reproduce

Can reproduce in safe-mode.

1. Prepare style to use keyframe animation on your `style.less`

```less
@keyframes t9md-test-animation {
  from { background-color: red; }
  to { background-color: transparent; }
}

atom-text-editor .t9md-test-flash .region {
  animation-name: t9md-test-animation;
  animation-fill-mode: forwards;
  animation-duration: 10.0s;
  animation-iteration-count: 1;
}
```

2. Open editor and prepare following text and select `line 2` to `line5`

```

line 2
line 3
line 4
line 5
```

3. Open chrome dev-console and paste following code.

This code copy selected text to clipboard and flash selected range which flash disappear after 10sec.

```javascript
(function flashreproduceIssue() {
  const editor = atom.workspace.getActiveTextEditor()
  editor.copySelectedText()
  const marker = editor.markBufferRange(editor.getSelectedBufferRange())
  editor.decorateMarker(marker, {type: "highlight", class: "t9md-test-flash"})
  setTimeout(function () {
    marker.destroy()
    console.log("destroyed");
  }, 10000);
})()
```

4. Within 10 sec, move to point `[0, 0]` and paste from clipboard and see original flash( keyframe animation ) is re-triggered.

What is happening here is
- Pasting 4 lines of text create new lines-tile and inserted **before** old line-tile
- At this timing, highlight node in old lines-tile is re-rendered.
- Which result in re-trigger of keyframe animation.

**Expected behavior:** [What you expect to happen]

Don't re-trigger keyframe animation.
Want highlight decoration node being stable once created.

**Actual behavior:** [What actually happens]

highlight decoration node is re-created when rendered line-tiles are changed.

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%.

### Versions

```
Atom    : 1.20.0-beta4
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0
```

```
Atom    : 1.18.0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

### Additional Information

Actual issue happened in https://github.com/t9md/atom-vim-mode-plus/issues/843.

### PR DESCRIPTION
**Pull request by as-cii**
As a consequence of https://github.com/atom/atom/pull/15378, we are now able to render highlight decorations in a separate div, as opposed to having an highlight container for each tile.

Code-wise this is much simpler, because highlights spanning multiple tiles can be represented via a single region and don't need to be split across the tiles they span anymore. As a byproduct, performance should improve as well, because the number of nodes that need to be managed should decrease significantly.

This also fixes https://github.com/atom/atom/issues/15449 (and other similar rendering artifacts), because highlight decoration DOM nodes won't need to move between tiles anymore when their position changes.

/cc: @nathansobo @t9md

### CODE REVIEW

File: src/text-editor-component.js [hunk 1]
```diff
@@ -4009,6 +3923,90 @@ class LineComponent {
   }
 }
 
+class HighlightsComponent {
+  constructor (props) {
+    this.props = {}
+    this.element = document.createElement('div')
+    this.element.className = 'highlights'
+    this.element.style.contain = 'strict'
```
Comment (as-cii) [inline src/text-editor-component.js]: @nathansobo: I tentatively set the layout containment to `strict` now that highlights are not inside tiles anymore. Previously, we were using only layout containment (which, as a side note, I don't think was being enforced by Chromium, because we wrote the property name and the value in the opposite order, e.g. `layout: contain` instead of `contain: layout`). 

Do you have any concerns about switching to a stricter form of containment? Rendering-wise everything seems to displayed correctly, but I'd love to have your input on this.

Comment (nathansobo) [reply src/text-editor-component.js]: If everything is working well it seems reasonable to apply strict layout containment. We can't apply it to the line tiles because we want to allow text to escape them at awkward line heights and the highlights need to show through from behind, correct?

**Comment by nathansobo** [comment]
👍

**Comment by t9md** [comment]
@as-cii This is not included in v1.20.0-beta6, any reason?
