### PR TITLE
Delete partially off-screen markers which are empty

### LINKED ISSUE #7183: Uncaught TypeError: Cannot read property 'highlights' of undefined
I was editing a CoffeeScript file, so I don't think this is related to the latex and xmllint packages I had installed at the time. It happened a few seconds after I unfolded a fold while editor had some search results highlighted.

Will try to reproduce, but so far I've been unsuccessful. cc @nathansobo for :eyes:

**Atom Version**: 0.208.0-c06d62e
**System**: Mac OS X 10.10.3
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: Cannot read property 'highlights' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1654

TypeError: Cannot read property 'highlights' of undefined
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateHighlightState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1654:25)
  at TextEditorPresenter.module.exports.TextEditorPresenter.updateDecorations (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:1518:18)
  at TextEditorPresenter.module.exports.TextEditorPresenter.getState (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-presenter.js:130:14)
  at TextEditorComponent.module.exports.TextEditorComponent.updateSync (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:182:38)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-component.js:298:28
  at ViewRegistry.module.exports.ViewRegistry.performDocumentUpdate (/Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:168:9)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/view-registry.js:3:61

```

### Commands

```
     -1:33.5.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:33.5.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:33.5.0 editor:indent (atom-text-editor.editor.is-focused)
  4x -1:33 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:08.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:07.6.0 core:backspace (atom-text-editor.editor.is-focused)
  6x -1:05.9.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -1:03.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  3x -1:02.2.0 editor:select-to-beginning-of-word (atom-text-editor.editor.is-focused)
  3x -1:00.4.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:56.7.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -0:39.4.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
  2x -0:38.4.0 core:backspace (atom-text-editor.editor.is-focused)
  5x -0:37.9.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:36.9.0 editor:select-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:07.3.0 editor:newline (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {},
  "editor": {
    "fontSize": 20,
    "invisibles": {},
    "softWrapAtPreferredLineLength": true,
    "showInvisibles": true,
    "tabLength": 4,
    "softWrap": true
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
linter, v0.12.6
linter-xmllint, v0.0.6

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by as-cii**
- :fire: Delete old code which was written to support some non-batched
  methods in a previous version;
- :white_check_mark: Cover “partially off-screen markers which are
  empty” scenario, since that [code path](https://github.com/atom/atom/blob/f830623512fe69c287f17fd5e02b9ad9dca401ad/src/text-editor-presenter.coffee#L1274) was not being hit by `TextEditorPresenter` specs;

Fixes #7183

/cc: @izuzak @nathansobo @maxbrunsfeld

### CODE REVIEW

File: src/text-editor-presenter.coffee [hunk 1]
```diff
@@ -1253,13 +1253,6 @@ class TextEditorPresenter
     range = marker.getScreenRange()
 
     if decoration.isDestroyed() or not marker.isValid() or range.isEmpty() or not range.intersectsRowRange(@startRow, @endRow - 1)
-      tileStartRow = @tileForRow(range.start.row)
-      tileEndRow = @tileForRow(range.end.row)
-
-      for tile in [tileStartRow..tileEndRow] by @tileSize
-        delete @state.content.tiles[tile]?.highlights[decoration.id]
-
-      @emitDidUpdateState()
```
Comment (as-cii) [inline src/text-editor-presenter.coffee]: This, as explained in this PR's description, was some leftover code which was useful when we updated highlight state right after an event was triggered. There isn't any un-batched method anymore now and, therefore, we can handle deletion right and only inside `@updateDecorations`. :art:

**Comment by maxbrunsfeld** [comment]
Awesome. Thanks for fixing this.

**Comment by izuzak** [comment]
Thanks, @as-cii :bow: Also just wanted to say _thank you_ for leaving a trail of helpful comments in your issues and PRs so that it's easier to understand what you're doing -- big :+1:.

**Comment by as-cii** [comment]
:heart:
