### PR TITLE
Move cursors container inside lines container

### LINKED ISSUE #15241: Cursor Position Indicator renders inside of characters
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

After upgrade from 1.18 to 1.19, Cursor position is broken and causes the cursor to show up INSIDE of the text, rather than the end of each character. See screenshot:
cursor-indicator

### Steps to Reproduce

1. Normal operation

**Expected behavior:** [What you expect to happen]
Cursor indicator between characters properly

**Actual behavior:** [What actually happens]
Cursor position renders inside of characters

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

1.19.0
You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
Windows 10 x64 (latest)
1080p with no dpi scaling.
Changing text size in atom.io has no effect

### PR DESCRIPTION
**Pull request by as-cii**
Fixes #15241.

This will ensure that applying any style that changes the location of the lines container will also correctly position the cursors.

@Ben3eeE @ungb: can you help me test this? I can't reproduce the issue anymore by using the `no-caffeine-syntax` theme or the personal stylesheet provided in https://github.com/atom/atom/issues/15241#issuecomment-322509336, but it'd be nice if you could give this a spin and ensure we didn't break anything else accidentally.

/cc: @nathansobo

### CODE REVIEW

File: spec/text-editor-component-spec.js [hunk 1]
```diff
@@ -479,14 +479,39 @@ describe('TextEditorComponent', () => {
...
       await component.getNextUpdatePromise()
-      const cursor = element.querySelector('.cursor')
       verifyCursorPosition(component, element.querySelector('.cursor'), 0, 3)
 
       editor.setCursorScreenPosition([0, 4])
       await component.getNextUpdatePromise()
       verifyCursorPosition(component, element.querySelector('.cursor'), 0, 4)
     })
 
+    it('positions cursors correctly when the lines container has a margin and/or is padded', async () => {
```
Comment (nathansobo) [inline spec/text-editor-component-spec.js]: Nice test.

**Review by nathansobo — APPROVED** [review]
Everything is the way it is for a reason, except when it isn't.

**Comment by Ben3eeE** [comment]
@as-cii @nathansobo 

With `no-caffeine-syntax` + `Soft Wrap` + `ctrl-scroll` the first line in the file renders other lines. I also see the cursor jumping down the line under the one where it currently is.

no-caffine syntax

no-caffine syntax 2

**Comment by nathansobo** [comment]
@Ben3eeE I can't reproduce either of these things on a fresh build of master at 586b818bae9886649da7d3fbdb231d419b0fbe90.

**Comment by Ben3eeE** [comment]
@nathansobo Same here. Fresh build of master at https://github.com/atom/atom/commit/586b818bae9886649da7d3fbdb231d419b0fbe90. Maybe it's a Windows only or something else going on. It reminds me of https://github.com/atom/find-and-replace/issues/868

**Comment by Ben3eeE** [comment]
@nathansobo @as-cii I see the same issue on a different computer running Windows 7 on a fresh build of Atom this morning. Here are the developer tools for this line:

image
