### PR TITLE
Fix Docks docs

### LINKED ISSUE #14728: Docks documentation points to non-existent get{Left|Right|Bottom}Dock methods
(Issue template does not apply)

The [Docks](https://atom.io/docs/api/v1.17.2/Dock) documentation links to `getLeftDock`, `getRightDock`, and `getBottomDock`.  However, there are two problems: those methods exist in Workspace and not Dock; and those methods are not publicly documented.

### PR DESCRIPTION
**Pull request by winstliu**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Fixes some issues with the new Docks documentation.  In particular, the documentation to `get{Left|Right|Bottom}Dock` was pointing to the wrong class and the methods themselves weren't public.

Please note: While adding documentation to the dock methods, I noticed that while `WorkspaceCenter` had docs for its individual methods, it did not have documentation for the class itself and therefore was not showing up as part of the API.  Therefore I've added a short blurb to the class.

The documentation I added was based off my best judgement and the comments for similar classes/methods; please feel free to improve them.

### Alternate Designs

N/A

### Why Should This Be In Core?

Because the documentation is in core.

### Benefits

Better documentation.

### Possible Drawbacks

None.

### Applicable Issues

Fixes #14728

I have no clue how to test this.

### CODE REVIEW

File: src/workspace.js [hunk 1]
```diff
@@ -1548,22 +1548,27 @@ module.exports = class Workspace extends Model {
...
   getRightDock () {
     return this.paneContainers.right
   }
 
+  // Essential: Get the {Dock} below the editor window.
   getBottomDock () {
     return this.paneContainers.bottom
   }
 
+  // Essential: Get an {Array} of the current {WorkspaceCenter} and {Dock}s.
```
Comment (jasonrudolph) [inline src/workspace.js]: Are we sure we want to make this method part of the public API?

I personally find this method's behavior a bit surprising. Specifically, I find it odd that this method returns a heterogenous collection of objects in which the objects have no explicit shared interface. I first ran into this in https://github.com/atom/atom/pull/14460#issue-229489706:

> It seems like there's an interface that we expect both `Dock` and `WorkspaceCenter` to implement, but I don't see that interface explicitly described or enforced anywhere. I _think_ that lack of explicit interface is a cause of the bug seen in #14442. There may be other bugs that are lurking due to code that implicitly expects a `WorkspaceCenter` and a `Dock` to provide a common interface.

Without an explicit interface that is shared by `WorkspaceCenter` and `Dock`, anyone using `Workspace::getPaneContainers()` will likely have to first check the type of each object in the collection before invoking any methods on that object.

If that sounds as odd to you as it does to me, I recommend excluding this method from the public API for now.

Comment (50Wliu) [inline src/workspace.js]: :+1: sounds good to me.  And if any package authors do want an array, they can just populate it themselves using the above four methods.

**Review by jasonrudolph — APPROVED** [review]
This looks good. Thanks for taking the time to make these updates! :bow:
