### PR TITLE
Fix  git diff subscriptions

### LINKED ISSUE #21630: git-diff: Doesn't detect subfolder as repos
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description

If you add a project folder which is not a git repo but it contains folders which are git repos, git diff won't work.
You can get it to work by adding the git repos as project folders, but it should be above the main project folder.

### Steps to Reproduce

1. Create the following tree:
|-- mainFolderWithoutGit
.....|-- someFolderWithGit
..........|-- .git
2. Add mainFolderWithoutGit as a project.
3. Make any changes to any file in someFolderWithGit

**Expected behavior:**

Changes should be detected by git-diff package

**Actual behavior:**

Changes are not detected

**Reproduces how often:**

100%

### Versions

1.52 and 1.53-beta0

### Additional Information

Fixed it here: https://github.com/atom/atom/pull/21631
Corresponding issue in tree-view: https://github.com/atom/tree-view/issues/1366

### LINKED ISSUE #21967: Small memory leak in package (git-diff) when enabled and disabled.
### Prerequisites

* [x ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: <https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode>
    * Followed all applicable steps in the debugging guide: <https://flight-manual.atom.io/hacking-atom/sections/debugging/>
    * Checked the FAQs on the message board for common solutions: <https://discuss.atom.io/c/faq>
    * Checked that your issue isn't already filed: <https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom>
    * Checked that there is not already an Atom package that provides the described functionality: <https://atom.io/packages>

### Description
When `git-diff` is disabled, it's GitDiffView instances aren't destroyed.

### Steps to Reproduce
1. Load Atom with the package enabled
2. Unload package.
3. Re-enable the package.
4. Repeat steps 2 and 3.

**Expected behavior:**
The GitDiffView instances should be destroyed when the editor is closed OR the package is disabled.

**Actual behavior:**
The GitDiffView's render contents are removed from the screen, but the objects aren't cleared and
remain in memory connected to the editor `onDidChangePath` and `onDidStopChanging` hooks until the editor is closed.

Here's [a Chromium Heap Profile of the allocations while turning the package on and off](https://drive.google.com/file/d/1j1UQ79R7sncgzAOZZYc5DNIijTCKeAgk/view?usp=sharing),
[a Chromium Heap Snapshot of the environment after turning things on and off, before garbage collection](https://drive.google.com/file/d/1pv5pURLCwnSsuKoF4lsr3oh4hkgTevll/view?usp=sharing),
and finally [a Chromium Heap Snapshot after forced garbage collection](https://drive.google.com/file/d/1HJDrbtB37UldlM4fQ7xvFn6iG9JrJyPB/view?usp=sharing)

**Reproduces how often:**
Always.

### Versions
Atom    : 1.53.0
Electron: 6.1.12
Chrome  : 76.0.3809.146
Node    : 12.4.0

### PR DESCRIPTION
**Pull request by M3TIOR**
### Identify the Bug
Was intended to fix bug #21966 but also fixes #21967

### Description of the Change
The startup script now uses a `Set` to manage `GitDiffView`s held in memory and destroy them when `deactivate` is called.
There are now four major subscription blocks. 
1. The outer subscriptions held by `activate`.
2. The per-editor subscriptions held within `activate`.
3. The per-editor repository event subscriptions held within each `GitDIffView` instance.
4. The per-editor modification event subscriptions held within each `GitDiffView` which are only active when the editor content is bound to avalid git repository.

Teardowns of any editor or the module now result in `dispose`al of the respective editor's subscriptions or all subscriptions authored within the module.

I removed some of `GitDiffView`'s unnecessary methods such as the `start`, `cancleUpdate`, `addDecoration` and `removeDecorations`;
The last two methods were combined into the body of `updateDiffs`.
`scheduleUpdate` now calls `requestAnimationFrame` instead of `setImmediate` because it's native, standard, and yields
to other more important browser processes. I know Atom Core implements setImmediate, but rAF seems to work just as fast if not faster.
The memory management of the editor markers and diffs have been joined using a WeakMap. When the diffs are destroyed,
so too are the editor markers.
Finally, I added the `destroy` method to handle teardown of subscriptions and other destroyable objects contained within the `GitDiffViews` before object release.

### Alternate Designs

I considered doing everything from within the main `activate` function, but decided against it because it's far more concise to put a lot of the functionality contained herein, into a single object.

### Possible Drawbacks

There's a warning in the source now; If the API for `git-utils` ever decides to re-use diff symbols between `repository.getLineDiffs` fetches, it could cause a memory leak due to my use of the `WeakMap` for allocation performance.

### Verification Process

I had to rewrite most of the existing specs to accomidate the async screen updates. I also added a test case to prevent regression of issue #21966. Beyond that, I tested modifying code and deleting lines, adding lines while in newly opened editors and turning the module on and off again between doing so.

I also check the Chromium memory profiler for leaks.
[Here's my heapprofile while flopping between the module on and off](https://drive.google.com/file/d/1T4pj5q5tM6LKe1_nAQ6tPqk6RJn41CJ7/view?usp=sharing),
[And here's the heapsnapshot sans forced garbage collection](https://drive.google.com/file/d/1DIX2grbiCgvyXIrzrIH3QzLfgmIlL9Ap/view?usp=sharing)

### Release Notes
 - Git Diff commands no longer accumulate when turning the package on and off.

### CODE REVIEW

**Comment by M3TIOR** [comment]
Dammit I just remembered I forgot to use JSDoc comments in the source code for better readability.  Oh well, I'll probs do that tomorrow when I'm not tired. Right after I fix the linter issue.

By the way, why does eslint throw different errors when running `eslint` and `script/lint`. Seems like some jank scripty buisness there. CoNdEnSe ThE LiNtEr SeTtInGs :P 

JK y'all probs have a good reason for it.

**Comment by M3TIOR** [comment]
Got board and did it tonight lol. Hopefully I can pass the automated test :laughing:

File: packages/git-diff/lib/git-diff-view.js [hunk 1]
```diff
@@ -1,64 +1,140 @@
...
+
+  async subscribeToRepository() {
+    if (this._repoSubs != null) {
+      this._repoSubs.dispose();
+      this.subscriptions.remove(this._repoSubs);
+    }
+
+    this.repository = await repositoryForPath(this.editor.getPath());
+    if (this.repository != null) {
+      const editorElm = atom.views.getView(this.editor);
```
Comment (calebmeyer) [inline packages/git-diff/lib/git-diff-view.js:79]: Can we name this `editorElement` instead? When I first saw it in the below code, I wondered what the Elm programming language had to do with git diffs.

File: packages/git-diff/lib/git-diff-view.js [hunk 2]
```diff
@@ -72,122 +148,106 @@ module.exports = class GitDiffView {
...
+      if (this.diffs)
+        for (const diff of this.diffs) this.markers.get(diff).destroy();
+
+      // WARNING: Could cause future memory leak if git-utils ever
+      // changes their diff strategy to one that re-uses diffs between
+      // requests. But that's unlikely to happen.
+      this.diffs = this.repository.getLineDiffs(path, this.editor.getText());
+      this.diffs = this.diffs || []; // Sanitize type to array.
+
+      for (let i = 0; i < this.diffs.length; i++) {
```
Comment (calebmeyer) [inline packages/git-diff/lib/git-diff-view.js:222]: Why use a for..of loop on 214 but a for index loop here? I don't see the loop index used except to access the array.

File: packages/git-diff/lib/main.js [hunk 3]
```diff
@@ -1,32 +1,52 @@
...
+        );
+      })
+    );
   },
 
   deactivate() {
-    if (diffListView) diffListView.destroy();
     diffListView = null;
+
+    for (const v of diffViews) v.destroy();
```
Comment (calebmeyer) [inline packages/git-diff/lib/main.js:46]:
```suggestion
    for (const diffView of diffViews) diffView.destroy();
```

File: packages/git-diff/lib/git-diff-view.js (hunk 1 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:79]: Yeah, I only shortened it so there would be fewer places the code had to wrap function calls. It was just easier for me to read that way. At least in my first itteration of the code.

File: packages/git-diff/lib/git-diff-view.js (hunk 2 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:222]: I'll fix that up too, it's a leftover artifact I forgot to clean up from when I tried using a single allocation array instead of that `WeakMap` for storing the markers.

File: packages/git-diff/lib/main.js (hunk 3 above)
Comment (M3TIOR) [reply packages/git-diff/lib/main.js:46]: That one I suppose I can *"fix"* too, although I don't see the problem since It's only a single line and it's very clear we're itterating through diffViews.

**Comment by M3TIOR** [comment]
May want to re-run the checks, it's failing @ the render process because it's calling a depricated method dock.getActiveTextEdtior()?

**Comment by M3TIOR** [comment]
Okay Azure, wtf? This worked the first time, I only added some comments and renamed a variable, now something completely unrelated to my code is failing?

File: packages/git-diff/lib/main.js (hunk 3 above)
Comment (aminya) [reply packages/git-diff/lib/main.js]: You'd better choose the words that are searchable by find and replace.  I suggestion this one:

```suggestion
    for (const diffView of diffViews) { 
		diffView.destroy();
	}
```

The above suggestion is debuggable (a breakpoint can be added), and it is also searchable

File: packages/git-diff/lib/git-diff-view.js [hunk 4]
```diff
@@ -1,64 +1,143 @@
...
+
+      const subscribeToRepository = this.subscribeToRepository.bind(this);
+      const updateIconDecoration = this.updateIconDecoration.bind(this);
+      const scheduleUpdate = this.scheduleUpdate.bind(this);
 
-    this.updateIconDecoration();
-    this.scheduleUpdate();
+      // Every time the repo is changed, the editor needs to be reinitialized.
+      this.subscriptions.add(
+        (this._repoSubs = new CompositeDisposable(
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:90]: Please avoid mixing returning and the assignment.

File: packages/git-diff/lib/git-diff-view.js [hunk 5]
```diff
@@ -1,64 +1,143 @@
...
+  /**
+   * @describe handles all subscriptions based on the repository in focus
+   */
+  async subscribeToRepository() {
+    if (this._repoSubs != null) {
+      this._repoSubs.dispose();
+      this.subscriptions.remove(this._repoSubs);
+    }
+
+    this.repository = await repositoryForPath(this.editor.getPath());
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:80]: `this.editor.getPath` function is called multiple times. Please cache it .

File: packages/git-diff/lib/git-diff-view.js [hunk 6]
```diff
@@ -1,64 +1,143 @@
...
-        if (newStart > cursorLineNumber) {
-          if (nextDiffLineNumber == null) nextDiffLineNumber = newStart - 1;
-          nextDiffLineNumber = Math.min(newStart - 1, nextDiffLineNumber);
-        }
 
-        if (firstDiffLineNumber == null) firstDiffLineNumber = newStart - 1;
-        firstDiffLineNumber = Math.min(newStart - 1, firstDiffLineNumber);
+    for (const { newStart } of this.diffs) {
+      if (newStart > cursorLineNumber) {
+        if (nextDiffLineNumber == null) nextDiffLineNumber = newStart - 1;
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:135]: Please use `{}`. This code is not debuggable and hard to see

File: packages/git-diff/lib/git-diff-view.js [hunk 7]
```diff
@@ -1,64 +1,143 @@
...
+   *   should only tear down objects that are selectively allocated upon
+   *   repository discovery.
+   *
+   *   Example: this.diffs only exists when we have a repository.
+   */
+  destroyChildren() {
+    if (this._animationId) cancelAnimationFrame(this._animationId);
+
+    if (this.diffs)
+      for (const diff of this.diffs) this.markers.get(diff).destroy();
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:57]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/git-diff-view.js [hunk 8]
```diff
@@ -1,64 +1,143 @@
...
 
-        if (firstDiffLineNumber == null) firstDiffLineNumber = newStart - 1;
-        firstDiffLineNumber = Math.min(newStart - 1, firstDiffLineNumber);
+    for (const { newStart } of this.diffs) {
+      if (newStart > cursorLineNumber) {
+        if (nextDiffLineNumber == null) nextDiffLineNumber = newStart - 1;
+        nextDiffLineNumber = Math.min(newStart - 1, nextDiffLineNumber);
       }
+
+      if (firstDiffLineNumber == null) firstDiffLineNumber = newStart - 1;
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:139]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/git-diff-view.js [hunk 9]
```diff
@@ -72,122 +151,106 @@ module.exports = class GitDiffView {
...
-  cancelUpdate() {
-    clearImmediate(this.immediateId);
-  }
-
   scheduleUpdate() {
-    this.cancelUpdate();
-    this.immediateId = setImmediate(this.updateDiffs);
+    // Use Chromium native requestAnimationFrame because it yields
+    // to the browser, is standard and doesn't involve extra JS overhead.
+    if (this._animationId) cancelAnimationFrame(this._animationId);
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:201]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/git-diff-view.js [hunk 10]
```diff
@@ -72,122 +151,106 @@ module.exports = class GitDiffView {
...
-      if (this.diffs) this.addDecorations(this.diffs);
-    }
-  }
+    const bufferLength = this.editor.getBuffer().getLength();
+    if (bufferLength < MAX_BUFFER_LENGTH_TO_DIFF) {
+      const path = this.editor.getPath();
+
+      // Before we redraw the diffs, tear down the old markers.
+      if (this.diffs)
+        for (const diff of this.diffs) this.markers.get(diff).destroy();
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:217]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/git-diff-view.js [hunk 11]
```diff
@@ -72,122 +151,106 @@ module.exports = class GitDiffView {
...
+
+      // WARNING: Could cause future memory leak if git-utils ever
+      // changes their diff strategy to one that re-uses diffs between
+      // requests. But that's unlikely to happen.
+      this.diffs = this.repository.getLineDiffs(path, this.editor.getText());
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:222]: You called `this.editor.getBuffer` in the above. You can get the text directly from the buffer. Please cache the buffer and call the needed methods.

File: packages/git-diff/lib/main.js [hunk 12]
```diff
@@ -1,32 +1,52 @@
...
-const DiffListView = require('./diff-list-view');
+'use babel';
+
+import { CompositeDisposable } from 'atom';
+import GitDiffView from './git-diff-view';
+import DiffListView from './diff-list-view';
 
 let diffListView = null;
+let diffViews = null;
+let subscriptions = null;
```
Comment (aminya) [inline packages/git-diff/lib/main.js:9]: You can call CompositeDisposable in the global scope and avoid a lot of null check. It is only a simple `new Set`

File: packages/git-diff/lib/main.js [hunk 13]
```diff
@@ -1,32 +1,52 @@
...
-
-      watchedEditors.add(editor);
-      editor.onDidDestroy(() => watchedEditors.delete(editor));
-    });
+        diffViews.add(diffView);
+
+        let editorSubs;
+        const command = 'git-diff:toggle-diff-list';
+        subscriptions.add(
+          (editorSubs = new CompositeDisposable(
```
Comment (aminya) [inline packages/git-diff/lib/main.js:26]: Please avoid mixing assignment and returning

File: packages/git-diff/lib/main.js [hunk 14]
```diff
@@ -1,32 +1,52 @@
...
+            atom.commands.add(editorElement, command, () => {
+              if (diffListView == null) diffListView = new DiffListView();
```
Comment (aminya) [inline packages/git-diff/lib/main.js:28]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/main.js [hunk 15]
```diff
@@ -1,32 +1,52 @@
...
+        );
+      })
+    );
   },
 
   deactivate() {
-    if (diffListView) diffListView.destroy();
     diffListView = null;
+
+    for (const diffView of diffViews) diffView.destroy();
```
Comment (aminya) [inline packages/git-diff/lib/main.js:46]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/git-diff-view.js [hunk 16]
```diff
@@ -1,64 +1,143 @@
...
+  /**
+   * @describe Destroys this objects children (non-freeing), it's intended
+   *   to be an ease-of use function for maintaing this object. This method
+   *   should only tear down objects that are selectively allocated upon
+   *   repository discovery.
+   *
+   *   Example: this.diffs only exists when we have a repository.
+   */
+  destroyChildren() {
+    if (this._animationId) cancelAnimationFrame(this._animationId);
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:54]: Please use `{}`. This code is not debuggable and hard to see the sentence

File: packages/git-diff/lib/git-diff-view.js [hunk 17]
```diff
@@ -1,64 +1,143 @@
...
+    this.diffs = null;
+    this._repoSubs = null;
+    this._animationId = null;
+  }
+
+  /**
+   * @describe handles all subscriptions based on the repository in focus
+   */
+  async subscribeToRepository() {
+    if (this._repoSubs != null) {
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:75]: Please assign it to null in the constructor, then:
```suggestion
    if (this._repoSubs !== null) {
```

File: packages/git-diff/lib/git-diff-view.js [hunk 18]
```diff
@@ -1,64 +1,143 @@
...
+      this._repoSubs.dispose();
+      this.subscriptions.remove(this._repoSubs);
+    }
+
+    this.repository = await repositoryForPath(this.editor.getPath());
+    if (this.repository != null) {
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:81]:
```suggestion
    if (this.repository !== null) {
```

File: packages/git-diff/lib/git-diff-view.js [hunk 19]
```diff
@@ -1,64 +1,143 @@
...
 
-    this.updateIconDecoration();
-    this.scheduleUpdate();
+      // Every time the repo is changed, the editor needs to be reinitialized.
+      this.subscriptions.add(
+        (this._repoSubs = new CompositeDisposable(
+          this.repository.onDidDestroy(subscribeToRepository),
+          this.repository.onDidChangeStatuses(scheduleUpdate),
+          this.repository.onDidChangeStatus(changedPath => {
+            if (changedPath === this.editor.getPath()) scheduleUpdate();
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:94]: Please use braces

File: packages/git-diff/lib/git-diff-view.js [hunk 20]
```diff
@@ -72,122 +151,106 @@ module.exports = class GitDiffView {
...
 
     this.moveToLineNumber(previousDiffLineNumber);
   }
 
-  moveToLineNumber(lineNumber) {
-    if (lineNumber != null && lineNumber >= 0) {
-      this.editor.setCursorBufferPosition([lineNumber, 0]);
-      this.editor.moveToFirstCharacterOfLine();
+  updateIconDecoration() {
+    const editorElement = atom.views.getView(this.editor);
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:177]: I see `atom.views.getView` many times. Please cache it in `this.editorElement`

File: packages/git-diff/lib/git-diff-view.js [hunk 21]
```diff
@@ -72,122 +151,106 @@ module.exports = class GitDiffView {
...
-          this.scheduleUpdate();
-        })
-      );
-      this.subscriptions.add(
-        this.repository.onDidChangeStatus(changedPath => {
-          if (changedPath === this.editor.getPath()) this.scheduleUpdate();
-        })
-      );
+  moveToLineNumber(lineNumber) {
+    if (lineNumber != null) {
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:192]: Are we sure that lineNumber is always more than 0?

File: packages/git-diff/lib/main.js [hunk 22]
```diff
@@ -1,32 +1,52 @@
...
-          diffListView.toggle();
-        }
-      );
-
-      watchedEditors.add(editor);
-      editor.onDidDestroy(() => watchedEditors.delete(editor));
-    });
+        diffViews.add(diffView);
+
+        let editorSubs;
```
Comment (aminya) [inline packages/git-diff/lib/main.js:23]: Just assign it directly if you need it somewhere else. See https://github.com/atom/atom/pull/21968/files#r578696295

File: packages/git-diff/lib/git-diff-view.js [hunk 23]
```diff
@@ -1,64 +1,143 @@
...
-    this.updateDiffs = this.updateDiffs.bind(this);
-    this.editor = editor;
+    // These are the only members guaranteed to exist.
     this.subscriptions = new CompositeDisposable();
-    this.decorations = {};
-    this.markers = [];
-  }
+    this.editor = editor;
+    this.repository = null;
+    this.markers = new WeakMap();
```
Comment (aminya) [inline packages/git-diff/lib/git-diff-view.js:18]: You can use a `Map` and use `clear()` function when they are destoryed.

Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:18]: But why add in extra effort if the garbage collector will already be running?

File: packages/git-diff/lib/git-diff-view.js (hunk 5 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:80]: ~~It's called once ever time the repository changes. It's not really that big of a deal since in my day-to-day I never change repositories as a user. While I can't use myself alone as a control group for the rest of Atom users, I don't think it's uses enough CPU time to warrant caching in RAM. CPU is more efficient than RAM.~~ Is the response I was going to use before I noticed that you're right and it gets called every redraw. Big oopsie my part.

File: packages/git-diff/lib/git-diff-view.js (hunk 4 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:90]: Okay, thought it was more readable like that.

File: packages/git-diff/lib/git-diff-view.js (hunk 20 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:177]: Okay

File: packages/git-diff/lib/main.js (hunk 12 above)
Comment (M3TIOR) [reply packages/git-diff/lib/main.js:9]: It's a single `null` check in the activate function that's only called once for the lifetime of the package. `null` occupies less memory than a set, so I figured I'd use that rather than leave extra memory hangin' around while the package is disabled.

File: packages/git-diff/lib/main.js (hunk 15 above)
Comment (M3TIOR) [reply packages/git-diff/lib/main.js:46]: Thanks for making me aware of how incomplete the chromium V8 JavaScript Debugging is lol. At first I didn't believe you because I've never had to debug a compound statement in JS before. Decided to try it out. Sucks. I'll fix those.

File: packages/git-diff/lib/git-diff-view.js (hunk 21 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:192]: A buffer only has 0-N array slots. It wouldn't make sense to use negative integer points to represent a buffer position unless it was relative to something else inside the same buffer. It's not in the [Atom Docs](https://flight-manual.atom.io/api/v1.54.0/TextEditor/#instance-getCursorBufferPosition). You're a maintainer right? You tell me. If it can be negative, add it to the docs please, so people like me can know to guard for it.

File: packages/git-diff/lib/git-diff-view.js (hunk 16 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:54]: To be clear, you really didn't need to comment on every single one of these. I got the point after the first one.

File: packages/git-diff/lib/main.js (hunk 3 above)
Comment (M3TIOR) [reply packages/git-diff/lib/main.js]: Your wording's a little confusing. I got the debugging bit from another comment, but what do you mean by 
> You'd better choose the words that are searchable by find and replace
Just because an itterable's variable name is a plural noun, doesn't mean all variables accessing it are guaranteed to use the same singular noun. Although that would be helpful for consistency.

Maybe I just answered my own question?

File: packages/git-diff/lib/git-diff-view.js (hunk 23 above)
Comment (ThatXliner) [reply packages/git-diff/lib/git-diff-view.js:18]: > But why add in extra effort if the garbage collector will already be running?

For style. IMO it'd add clarity, telling one reading the code that you are not going to use the Map anymore

Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:18]: True. I prefer this way because it doesn't block the render pipeline. I want the draw function to run as fast as possible. I was thinking about making a future contribution which optimized redraws by modifying the cached set of diffs instead of regenerating it every redraw which would cut down on memory releases within the `WeakMap`; the diffs can't be helped because that's an API issue with `git-utils`, but the markers can. By simply swapping the changed diffs within it's array, the `WeakMap` removes the corresponding markers without extra memory management. This method makes it easier for me to write those future modifications.

File: packages/git-diff/lib/main.js (hunk 15 above)
Comment (DeeDeeG) [reply packages/git-diff/lib/main.js:46]: I can usually set breakpoints anywhere within a line of code. On any method, usually. So I would be able to set one on `.destroy()` I think, if that's what you mean @aminya.

Using `chrome://inspect` in Google Chrome of macOS 10.15.7.

**Review by aleee1333 — APPROVED** [review]

**Review by aleee1333 — APPROVED** [review]

File: packages/git-diff/lib/git-diff-view.js (hunk 23 above)
Comment (aminya) [reply packages/git-diff/lib/git-diff-view.js:18]: `WeakMap` does not guarantee the removal! We have a hard requirement for removing the entries when they are destroyed, otherwise, we will keep the markers that are destroyed!

See this video to understand more about weak references:
https://youtu.be/uygxJ8Wxotc

File: packages/git-diff/lib/main.js (hunk 15 above)
Comment (aminya) [reply packages/git-diff/lib/main.js:46]: Even if you can debug this inside the latest Chrome, you can't do it inside Atom. 

This is a not-so-good style of coding. There are other things that are wrong with them.

See this video from Tony Van Erd to learn more:
https://youtu.be/GPP64opjy_Y?t=1068

**Comment by M3TIOR** [comment]
Finally back home and at my Laptop to get those issues fixed. Sorry it's been taking so long.

File: packages/git-diff/lib/git-diff-view.js (hunk 18 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:81]: Why is this change warranted? It's a microsecond optimization at best. Checking lazy null is more robust than checking strict null in case the object somehow becomes undefined. If that be in a future update or otherwise.

File: packages/git-diff/lib/git-diff-view.js (hunk 21 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:192]: Yes, I modified the algorithms in the `moveToNextDiff` and `moveToPreviousDiff` methods to both return `null` or a positive integer. At least within Atom's spec. It's to my understanding that `Atom.TextEditor.getCursorBufferPosition()` returns a `Point`. It wouldn't make sense to return a negative graph `Point` using said method because buffer memory accesses are intuitively linear. Admittedly this is a bit presumptuous of me, and we all know deterministic behavior is better. So I'll look into the Atom internals in a bit to figure out if this is actually an issue and if it is, I'll update the docs so nobody else has to apply intuition for that method. I'll also update this thread with my findings either way so we're all on the same page.

But right now I have a COVID test to attend to.

Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:192]: So `Atom.TextEditor.getCursorBufferPosition` eventually calls `Atom.TextBuffer.getMarkerStartPosition` containing the code:
```
Point.fromObject(@index.getStart(id))
```
*@index* is a `superstring` library method `marker` which only fetches a positive `row` and `column`.

File: packages/git-diff/lib/git-diff-view.js (hunk 23 above)
Comment (M3TIOR) [reply packages/git-diff/lib/git-diff-view.js:18]: Thanks for the informative videos. Really appreciated! I'll go ahead and change that to a `Map` then.

File: packages/git-diff/lib/main.js (hunk 15 above)
Comment (DeeDeeG) [reply packages/git-diff/lib/main.js:46]: > Even if you can debug this inside the latest Chrome, you can't do it inside Atom.

For what it's worth: We do continue to get newer Chrome via newer Electron. That's one good reason to finish work on the Electron 9 upgrade (https://github.com/atom/atom/pull/21777).

**Comment by M3TIOR** [comment]
That officially took way too long. I'll consider making a PR for the `.eslint.json` configuration changes since I found a conflict between the `prettier/prettier` settings and the `eslint` ones. That *and* @aminya is right, *things should be debuggable by default* regardless of the core Electron version; I discovered a few compound statements within the Atom core that should be `--fix` and maintainable once the eslint changes are made.

Untill then, this currently uses styling that goes against the Atom `script/lint` settings and will be destroyed if run with `--fix` prior to the changes. I'll leave it up to the maintainers to take care of that.

**Comment by M3TIOR** [comment]
```json
"rules": {
    "nonblock-statement-body-position": ["error", "below"]
  },
```

That's the rule I added to the eslint config just so everybody's aware.

**Comment by M3TIOR** [comment]
Windows Renderer test and Linter is failing. The Windows Render test failure seems to be a recurrent issue that happens infrequently. Can it be overlooked or do I need to make another commit to refresh it.

**Comment by aminya** [comment]
You need to run `script/lint --fix` to fix the linting error.

> Windows Renderer test and Linter is failing. The Windows Render test failure seems to be a recurrent issue that happens infrequently. Can it be overlooked or do I need to make another commit to rerun it?

That is just a timeout. These happen sometimes in the CI.

File: packages/git-diff/lib/git-diff-view.js (hunk 18 above)
Comment (aminya) [reply packages/git-diff/lib/git-diff-view.js]: Does `this.repository` become `undefined` anywhere in this code? If not, there is no need to use a fuzzy comparison.

File: packages/git-diff/lib/git-diff-view.js (hunk 17 above)
Comment (aminya) [reply packages/git-diff/lib/git-diff-view.js]: This is one is not fixed yet. Please fix.

**Comment by M3TIOR** [comment]
@aminya Like I said, running `script/lint` with `--fix` would overwrite the manual styling that fixed the debuggability issues. I refuse to add brackets to single line queries that won't ever need extension. It makes the code look bloated. So I did what that C++ seminar recommended and enforced line breaks in compund statements so breakpoints can be added to the internals.

**Comment by aminya** [comment]
You need to add the braces so Prettier styles it correctly. This is what all the Atom code uses. Please follow the style.

**Comment by M3TIOR** [comment]
So why then do you allow compound statements to exist in the code at all? Are you trying to enforce a personal standard outside of the maintainer's wishes?

**Comment by aminya** [comment]
That's how the Atom's coding style not mine.

**Comment by M3TIOR** [comment]
So then it's a non-issue and a personal criticism.

**Comment by M3TIOR** [comment]
So you admit that my original styling was fine then, because it didn't conflict with Atom's styling. And you're saying I should revert it?

**Comment by aminya** [comment]
You are misunderstanding my review. The style I suggested is Atom's coding style not what you prefer to do in this PR. Your style is alien to this codebase.

Examples:
https://github.com/atom/atom/blob/eb064bf502cc91c7209546544973bdbdad054394/packages/grammar-selector/lib/grammar-list-view.js#L13-L15

https://github.com/atom/atom/blob/eb064bf502cc91c7209546544973bdbdad054394/packages/grammar-selector/lib/grammar-list-view.js#L68-L71

https://github.com/atom/atom/blob/eb064bf502cc91c7209546544973bdbdad054394/packages/go-to-line/lib/go-to-line-view.js#L33-L35

and a billion other examples.

**Comment by DeeDeeG** [comment]
@aminya while I believe you are coming from a good place, I think it's time to stop with the style comments. This PR represents a lot of effort, which should be respected. I do not think pursuing the style review to this level is warranted. If hypothetically it was, I would ask that you please make the review in the form of an optional suggestion and be willing to accept a "no" answer. No-one who has responded thus far is an official maintainer of the Atom repository. If the author of this PR prefers not to make a style change you suggest, that's okay. None of us has authority to insist otherwise. If a hard dispute arises, which it has, it is polite to let the maintainers decide rather than continue to make the point. Thanks.

**Comment by aminya** [comment]
My suggestions are by no means discouraging contributions (e.g. among all the people, it's only me who has given thumbs up to the changes). My suggestions are just to help to use the best practices and use a style that fits that particular codebase. 

> I think it's time to stop with the style comments. 

Not following a unified style results in a spaghetti code in which each part comes from a different world, and each part is alien to other parts.

**Comment by M3TIOR** [comment]
@aminya I just want to call out your balognia. Please investigate and validate your own claims before you make them.

[src/text-editor.js:104](https://github.com/atom/atom/blob/master/src/text-editor.js)
```javascript
if (state.version !== SERIALIZATION_VERSION) return null;
```
[src/text-editor.js:112](https://github.com/atom/atom/blob/master/src/text-editor.js)
```javascript
if (!state.buffer) return null;
```
[src/text-editor.js:290](https://github.com/atom/atom/blob/master/src/text-editor.js)
```javascript
f (!this.isMini()) this.decorateCursorLine();
```

[There are hundreds more examples of this which can be easily pointed out if you just run the linter with the settings I highlighted above.](https://pastebin.com/twfWDNsg)

**Comment by aminya** [comment]
What I have learned by contributing to hundreds of projects on GitHub is to follow the coding paradigms/conventions that a specific project is using instead of guarding against the reviewers. This has given my PRs a very high chance of getting approved. No matter if I am an OOP guy or a functional guy, or if I hate braces, I know how to follow what the reviewers suggest to facilitate getting my change inside. At the end of the day, it is the "main contribution" that matters the most.

If you like making the code undebuggable, that is fine with me, and I will not stop you from doing that. But remember that contributing to shared projects requires a different mindset compared to personal projects, and you should consider "all the other developers."

In the same video I gave you before, Tony Van Eerd nails this "People already have enough paradigms."
https://youtu.be/GPP64opjy_Y?t=1668

**Comment by M3TIOR** [comment]
Are you kidding me? So this is my problem alone, and I shouldn't try and help the **whole project** by making a PR for suitable linter changes? Because that was my next step, and I think it should have been yours as well. If you knew about this issue and didn't say anything besides to harrass a new contributor, then *you have no room to talk*. I'm going to try and fix this issue at the core. If you want to **make a review and help get those changes submitted** then I'd appreciate the help. Otherwise please stop complaining.

**Comment by aminya** [comment]
I am going to stop commenting on this PR due to the shocking feedback I have received. You can do whatever you feel is OK for your project.

**Comment by M3TIOR** [comment]
So I'm making a revision to fix the linting issue and I'm having a hard time. It seems like the `"nonblock-statement-body-position"` eslint setting, conflicts with prettier's oppinionated formatting choices. Trying to add the setting in the .eslintrc results in unresolvable errors. I tried using `prettier-eslint-cli` and that was a hellstorm. I'm stuck. It seems like the maintainers really like Prettier since it's standard in the `CONTRIBUTING.md`. I'm thinking the styling issue is a `"nofix"` issue. Which is okay, considering the upgrade to the internal Electron Version comming in soon sounds like it might fix the debuggability issue.

It's still beyond me what Prettier provides over ESlint alone. I'll hopefully pick it up sometime in the future. Too tired to pick it up right now.

**Comment by DeeDeeG** [comment]
I looked into this a bit. It seems ESLint is very flexible and configurable. And Prettier is meant to be opinionated and not configurable. Any integration between Prettier and ESLint is apparently meant to turn off rules in ESLint that conflict with Prettier.

Not to get too off-topic, but for my part, I can't even run `script/lint` all the way through for the project without getting an out of memory error.

<details><summary>Error message from script/lint</summary>

```
% script/lint
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x101203f65 node::Abort() (.cold.1) [[path/to]/node]
 2: 0x1000a5a09 node::Abort() [[path/to]/node]
 3: 0x1000a5b6f node::OnFatalError(char const*, char const*) [[path/to]/node]
 4: 0x1001eeb97 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [[path/to]/node]
 5: 0x1001eeb37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [[path/to]/node]
 6: 0x100387b55 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [[path/to]/node]
 7: 0x1003893ca v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [[path/to]/node]
 8: 0x100385dfc v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [[path/to]/node]
 9: 0x100383bfe v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [[path/to]/node]
10: 0x10038faca v8::internal::Heap::AllocateRawWithLightRetry(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [[path/to]/node]
11: 0x10038fb51 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [[path/to]/node]
12: 0x10035d42a v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [[path/to]/node]
13: 0x1006aff78 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [[path/to]/node]
14: 0x100a0ca79 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [[path/to]/node]
```

</details>

(Personally, I either let CI run the lints, or I run `prettier` from the CLI: `cd script` and to check if I pass the lint I do `npx prettier -c ../path/to/file.js`. And if I want to have Prettier do its thing and overwrite the file, I stash, stage or commit my changes, then do `npx prettier -w ../path/to/file.js`.)

**Comment by DeeDeeG** [comment]
I can confirm from testing this change that the "Git Diff" commands don't pile up/duplicate in the Command Palette anymore. (As described in the linked issue https://github.com/atom/atom/issues/21966).

**Review by DeeDeeG — APPROVED** [review]
I'm approving this due to the fact that, in my testing, this solves the primary issue it is meant to solve. https://github.com/atom/atom/issues/21966

I'm honestly not super fluent with JS, so I am not reviewing the code changes, just confirming that this PR works in my testing.

_(Hoping that some approvals will encourage maintainers to take a look at this.)_

**Review by sadick254 — APPROVED** [review]
I have confirmed that this works as expected. Thanks @M3TIOR for all the hard work on this PR. Thanks @DeeDeeG for your review as well.
