### PR TITLE
🚱 Fix leak of LanguageMode objects in tests

### LINKED ISSUE #18991: Flaky build: Windows build sometimes fails with "resource busy or locked"
In our Windows 64-bit builds, we frequently see the build fail at this point in the test suite...

```
...
TextEditor > buffer manipulation > .outdentSelectedRows() > when one line is selected > outdents line and retains editor Renderer process crashed, exiting
EBUSY: resource busy or locked, unlink 'C:\Users\VSSADM~1\AppData\Local\Temp\atom-test-data119118-3988-dplic9.gszd4\databases\Databases.db'
Error: EBUSY: resource busy or locked, unlink 'C:\Users\VSSADM~1\AppData\Local\Temp\atom-test-data119118-3988-dplic9.gszd4\databases\Databases.db'
    at Object.fs.unlinkSync (fs.js:1061:3)
    at rimrafSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
    at D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>:null:null)
    at rmkidsSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:216:26)
    at D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:245:5
    at Array.forEach (<anonymous>:null:null)
    at rmkidsSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:244:26)
    at rmdirSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:237:7)
    at fixWinEPERMSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:150:5)
    at rimrafSync (D:\a\1\s\node_modules\temp\node_modules\rimraf\rimraf.js:216:26)
    at cleanupDirsSync (D:\a\1\s\node_modules\temp\lib\temp.js:143:5)
    at process.cleanupSync (D:\a\1\s\node_modules\temp\lib\temp.js:196:19)
    at process.emit (events.js:187:15)
    at App.<anonymous> (D:\a\1\s\out\Atom Dev x64\resources\electron.asar\browser\init.js:64:11)
    at App.emit (events.js:182:13)
    at AtomApplication.exit (D:\a\1\s\src\main-process\atom-application.js:99:9)
    at WebContents.browserWindow.webContents.on (D:\a\1\s\src\main-process\atom-window.js:180:30)
    at WebContents.emit (events.js:182:13)
```

Rebuilding can sometimes resolve the failure.

---

**Affected CI provider(s)**: AppVeyor, Azure DevOps

**Affected platform(s)**: Windows 64-bit

**Example commit experiencing flakiness**: https://github.com/atom/atom/commit/8d8e39d0f85dfe96c1985c3d0159c3c1bba10c22

**Example failing build at that commit**: https://ci.appveyor.com/project/Atom/atom/builds/22070045/job/ooh3881g6b53avyn

**Example passing build at that commit**: https://ci.appveyor.com/project/Atom/atom/builds/22070428/job/t68iykoniojgy7tw

**Example log from failing build**: https://github.com/atom/atom/files/2967489/build.log

### PR DESCRIPTION
**Pull request by nathansobo**
Fixes #18991

In #18991, we were experiencing render process crashes caused by the render process running out of memory. Upon investigating, we discovered that the memory used by the `Atom Helper` process rapidly increased during `text-editor-spec.js`, from a couple hundred megabytes to 3+ gigabytes by the end of those tests.

We were confused, because a heap snapshot of the process indicated a normal heap size of just a couple hundred megabytes. Upon further investigation, I discovered that we were leaking `TextMateLanguageMode` objects. These language modes reference TextMate grammars, which themselves reference a large number of Oniguruma regular expression objects, which are implemented in a native C++ and therefore not tracked as part of the JS heap. That explains the discrepancy between the process memory consumed and what was being reported in the Chrome dev tools.

The cause of the leak was subtle. In `TextEditorRegistry`, we were assigning a promise to an instance field named `initialPackageActivationPromise`. This would resolve when the `PackageManager` emitted an `onDidActivateInitialPackages` event. We then `await`ed this promise in `updateAndMonitorEditorSettings`, and this ended up implicitly capturing the `oldLanguageMode` variable that we interacted with after resuming from the `await`. Unfortunately, in many tests, we never emit the `onDidActivateInitialPackages` event at all, so this promise was hanging around unresolved. This was causing the `oldLanguageMode` to be kept in scope by the `initialPackageActivationPromise` we were `await`ing. Not sure how clear that was, but hopefully it helps explain the diff to a careful reader.

My solution is to expose a `getActivatePromise` method on the `PackageManager` itself. We store off the promise during activation and then null it out when we're done. Most importantly, we *also* null out this promise when we call `PackageManager.prototype.reset`, so that any objects that are implicitly captured by code `await`ing this promise get garbage collected.

As a result, we end `text-editor-spec.js` with 6 `TextMateLanguageMode` objects on the heap instead of 954, and the memory consumed by the process is kept more reasonable (though Jasmine still seems to be leakier than I'd prefer).

### Before:

Screen Shot 2019-05-17 at 4 32 37 PM

### After:

Screen Shot 2019-05-17 at 4 39 15 PM

### CODE REVIEW

File: src/package-manager.js [hunk 1]
```diff
@@ -674,6 +674,7 @@ module.exports = class PackageManager {
       this.emitter.emit('did-activate-initial-packages')
       this.activatePromise = null
     })
+    return this.activatePromise
```
Comment (nathansobo) [inline src/package-manager.js]: Oops, thanks.
