### PR TITLE
"Open file" in existing window

### LINKED ISSUE #19133: "Open file..." opens a new window
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: https://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: https://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

On Windows, when opening a file using the "Open file..." item from the app menu, the file gets opened in a new Atom window instead of reusing the existing window.

### Steps to Reproduce

1. Open Atom.
2. Go to "File" -> "Open file..." and open a random file.

**Expected behavior:** The file should get opened in the same Atom window.

**Actual behavior:** a new Atom window gets opened.

**Reproduces how often:** Always.

### Versions

This started failing on the 1.36 branch.

### Additional Information

N/A

### PR DESCRIPTION
**Pull request by smashwilson**
### Requirements for Contributing a Bug Fix

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix an existing bug. To contribute other changes, you must use a different template. You can see all templates at https://github.com/atom/atom/tree/master/.github/PULL_REQUEST_TEMPLATE.
* The pull request must update the test suite to demonstrate the changed functionality. For guidance, please see https://flight-manual.atom.io/hacking-atom/sections/writing-specs/.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see https://github.com/atom/atom/tree/master/CONTRIBUTING.md#pull-requests.

### Identify the Bug

Fixes #19133.

### Description of the Change

In AtomApplication:

* Made the `getLoadSettings()` helper optionally include the last focused window in its output.
* Modified `openPaths()` to more strongly respect an explicitly provided `{window}` argument. (Previously, `{window}` would be used only if `{addToLastWindow}` was set to true.)
* Changed `promptForPathsToOpen()` to pass a `{window}` argument on to `openPaths()` if and only if all of the chosen paths are non-directories. (This is to be consistent with the behavior in 1.35.1; "open folder" opens a new window, "open file" opens in the existing window.)
* Used `getLoadSettings(true)` in all of the codepaths that an "open" or "open file" dialog can hit.

### Alternate Designs

We could refactor the opening logic completely I guess to be clearer and less error-prone. Now isn't the time to do that, though, and it went poorly the last time I tried it.

### Possible Drawbacks

`application:open-file` and `application:open-folder` have inconsistent and confusing behavior.

### Verification Process

I did a manual Atom build and verified that the File -> Open... menu item and the `cmd-O` keybinding opened files in the current window and folders in a new window.

### Release Notes

This is fixing a regression, so no release notes.

### CODE REVIEW

**Comment by jasonrudolph** [comment]
> ### Possible Drawbacks
> `application:open-file` and `application:open-folder` have inconsistent and confusing behavior.

@smashwilson: Am I correct in thinking that this inconsistent/confusing behavior predates this pull request (i.e., that this has been Atom's behavior for a while now)?

**Comment by smashwilson** [comment]
@jasonrudolph: Yup - basically, I downloaded Atom 1.35.1 and did my best to match its behavior.

Oh, also, our test coverage for AtomApplication is not great. I'd take the time to add tests for this, but ugh.

File: src/main-process/atom-application.js [hunk 1]
```diff
@@ -1412,14 +1426,32 @@ class AtomApplication extends EventEmitter {
...
+        // new window instead.
+        if (type === 'folder') {
+          targetWindow = null
+        } else if (type === 'file') {
+          targetWindow = window
+        } else if (type === 'all') {
+          const areDirectories = await Promise.all(
+            pathsToOpen.map(pathToOpen => new Promise(resolve => fs.isDirectory(pathToOpen, resolve)))
+          )
+          if (!areDirectories.some(Boolean)) {
```
Comment (jasonrudolph) [inline src/main-process/atom-application.js]: Current status: Wishing JavaScript Array provided a [`none` method](https://ruby-doc.org/core-2.6.2/Enumerable.html#method-i-none-3F).

File: src/main-process/atom-application.js [hunk 2]
```diff
@@ -452,13 +452,17 @@ class AtomApplication extends EventEmitter {
...
+      return {
+        devMode: window && window.devMode,
+        safeMode: window && window.safeMode,
+        window: includeWindow && window
+      }
     }
 
     this.on('application:quit', () => app.quit())
-    this.on('application:new-window', () => this.openPath(getLoadSettings()))
+    this.on('application:new-window', () => this.openPath(getLoadSettings(false)))
```
Comment (jasonrudolph) [inline src/main-process/atom-application.js]: This isn't something that should hold up this pull request, but I think calls to `getLoadSettings` could be more intention-revealing/self-documenting we used a named argument. 

```js
getLoadSettings({includeWindow: false})
```

What do you think?

**Review by jasonrudolph — COMMENTED** [review]
@smashwilson: Thanks for jumping on this. :bow:💟

Do you anticipate this pull request resulting in any changes on other platforms (i.e., Linux and macOS)? Would it make sense try out a build on those other platforms to ensure that it's behaving as expected?

File: src/main-process/atom-application.js (hunk 1 above)
Comment (smashwilson) [reply src/main-process/atom-application.js]: Yeah... I spent a little time trying to juggle this in a way that was more readable, but I didn't have much luck. Notably I couldn't avoid the negative by looking for files instead because paths that don't exist yet are also not "files". And negating it to produce `notDirectories` just made it worse 🙃

File: src/main-process/atom-application.js (hunk 2 above)
Comment (smashwilson) [reply src/main-process/atom-application.js]: Yah, that's reasonable. Honestly this whole class could use an overhaul to its readability. I tried to at least leave comments where I was changing things.

**Review by smashwilson — COMMENTED** [review]
Thanks @jasonrudolph 🙇

**Comment by smashwilson** [comment]
> Do you anticipate this pull request resulting in any changes on other platforms (i.e., Linux and macOS)? Would it make sense try out a build on those other platforms to ensure that it's behaving as expected?

This will actually have the same behavior on all three, although the menu items present in the "file" menu differ from platform to platform. I tested builds on macOS by running commands from the command palette. But I'll be sure to give it a final check on the others.

**Comment by trisa88** [comment]
Help mi
