### PR TITLE
Handle native chromium undo, redo, cut, copy, paste, selectAll on all platforms

### LINKED ISSUE #6587: Uncaught TypeError: undefined is not a function on Undo operations for special panes
Steps to recreate.

1. Open Timecop or the Styleguide
2. Perform an Undo (Redo also causes problem in Timecop)

**Atom Version**: 0.193.0
**System**: linux 3.19.3-3-ARCH
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app.asar/src/window-event-handler.js:164

TypeError: undefined is not a function
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:164:20)
  at HTMLDocument.handler (/usr/share/atom/resources/app.asar/src/space-pen-extensions.js:115:32)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app.asar/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:238:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:153:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:71:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -3:31 timecop:view (atom-text-editor.editor.vim-mode.command-mode)
     -2:29 core:undo (div.timecop.pane-item.native-key-bindings)
     -1:40.7.0 settings-view:open (div.timecop.pane-item.native-key-bindings)
     -1:36.5.0 core:undo (div.settings-view.pane-item)
     -1:34.8.0 core:redo (div.settings-view.pane-item)
     -1:29 open-on-github:file (div.timecop.pane-item.native-key-bindings)
     -1:06.5.0 core:undo (div.timecop.pane-item.native-key-bindings)
     -0:00.5.0 core:redo (div.timecop.pane-item.native-key-bindings)
```

### Config

```json
{
  "core": {
    "useReactEditor": true,
    "disabledPackages": [
      "minimap",
      "symbols-view"
    ]
  },
  "editor": {
    "softWrap": true,
    "invisibles": {},
    "fontFamily": "monospace",
    "fontSize": 17
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v3.2.0
atom-html-preview, v0.1.6
autocomplete-plus, v2.12.1
color-picker, v1.7.0
language-puppet, v0.11.0
linter, v0.12.1
linter-cpplint, v0.1.4
linter-jshint, v0.1.2
linter-pep8, v0.1.0
vim-mode, v0.45.0

# Dev
No dev packages
```

### PR DESCRIPTION
**Pull request by nathansobo**
Our current approach relies on `menu.sendActionToFirstResponder`, which is only defined on OS X. It would be good to actually make this work elsewhere, but this will at least prevent the exception for the undefined method.

Closes #6587

### CODE REVIEW

**Comment by paulcbetts** [comment]
I know this one, I know this one! Start here: https://github.com/atom/electron/blob/master/docs/api/browser-window.md#webcontentsundo

**Comment by nathansobo** [comment]
@paulcbetts Thanks for that. Check out the amended PR. I would actually like to always handle these commands if they bubble to the root of the document without the default being prevented or propagation being stopped, but changing the behavior now might introduce unintended consequences. I'm just going to fix the exception for now.

**Comment by paulcbetts** [comment]
@nathansobo Seems Legit™

File: src/window-event-handler.coffee [hunk 1]
```diff
@@ -114,23 +114,23 @@ class WindowEventHandler
...
+  # Wire commands that should be handled by Chromium for elements with the
+  # `.native-key-bindings` class.
   handleNativeKeybindings: ->
     menu = null
     bindCommandToAction = (command, action) =>
       @subscribe $(document), command, (event) ->
         if event.target.webkitMatchesSelector('.native-key-bindings')
-          menu ?= require('remote').require('menu')
-          menu.sendActionToFirstResponder(action)
+          webContents = require('remote').getCurrentWindow().webContents
```
Comment (kevinsawicki) [inline src/window-event-handler.coffee]: Just a heads up, there is an `atom.getCurrentWindow()` API

Comment (nathansobo) [inline src/window-event-handler.coffee]: Oh jeez you're right.
