### PR TITLE
Make sure path is not undefined (#20871)

### LINKED ISSUE #20871: Uncaught TypeError: The "path" argument must be of type string. Received type undefined
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.47.0 x64
**Electron**: 5.0.13
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: The "path" argument must be of type string. Received type undefined

```
At internal/validators.js:105

TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:105:11)
    at Object.join (path.js:372:7)
    at ~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:24548
    at Array.map (<anonymous>)
    at watcher.c.debounceMS (~/AppData/Local/atom/app-1.47.0/resources/app/static/<embedded>:14:24400)
```

### Commands

```
     -0:50.3.0 julia-client:start-julia (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
hyperclick 0.1.5 
indent-detective 0.4.0 
ink 0.12.4 
julia-client 0.12.5 
language-julia 0.19.3 
latex-completions 0.3.6 
tool-bar 1.3.0 
uber-juno 0.3.0 
```

### PR DESCRIPTION
**Pull request by bennyborn**
### Identify the Bug

This fixes a bug where upating the rights (CHMOD) of files mounted on a SMB share causes the path watcher to create an invalid path (see #20871)

### Description of the Change

While I do not understand the exact origins how this bug comes together, I still managed to provide a very obvious fix for something that should be a string rather than `undefined`.

### Alternate Designs

none

### Possible Drawbacks

none

### Verification Process

Working with files from a SMB share (Windows host) on a daily basis it is as simple as having open a SMB mounted directory and updating the rights of the folder via `chmod -R 775`.

### Release Notes

Fixed an error that occurs when working with files from a SMB share

### CODE REVIEW

**Comment by icecream17** [comment]
@bennyborn We still haven't made it to babel 7 yet, so unforunately you can't use the nullish coalescing operator.

Also add spaces around the operators, because the tests include a linter

File: src/path-watcher.js [hunk 1]
```diff
@@ -294,8 +294,8 @@ class NSFWNativeWatcher extends NativeWatcher {
           if (event.file) {
             payload.path = path.join(event.directory, event.file);
           } else {
-            payload.oldPath = path.join(event.directory, event.oldFile);
-            payload.path = path.join(event.directory, event.newFile);
+            payload.oldPath = path.join(event.directory, event.oldFile??'');
```
Comment (icecream17) [inline src/path-watcher.js:297]:
```suggestion
            payload.oldPath = path.join(event.directory, event.oldFile == undefined ? '' : event.oldFile);
```

File: src/path-watcher.js [hunk 2]
```diff
@@ -294,8 +294,8 @@ class NSFWNativeWatcher extends NativeWatcher {
...
+            payload.path = path.join(event.directory, event.newFile??'');
```
Comment (icecream17) [inline src/path-watcher.js:298]:
```suggestion
            payload.oldPath = path.join(event.directory, event.oldFile == undefined ? '' : event.oldFile);
            payload.path = path.join(event.directory, event.newFile == undefined ? '' : event.newFile);
```

**Comment by bennyborn** [comment]
@icecream17 Thanks. Haven't looked into the checks since this morning.

**Review by sadick254 — COMMENTED** [review]
Can we please have some specs on this PR?

**Comment by bennyborn** [comment]
> Can we please have some specs on this PR?

I'm not quite sure what you mean by that. What do you need?

**Comment by icecream17** [comment]
spec = test

**Comment by bennyborn** [comment]
> I don't know much about creating tests though - but I'd say that https://github.com/atom/atom/blob/master/spec/path-watcher-spec.js would be the file to change

That makes two of us. I could try if I had any clue how the original problem occured in the first place but as stated in my first post I can only provide a fix, not an explanation :\

**Comment by DeeDeeG** [comment]
A test that sets up `event.oldFile` and `event.newFile` to be `undefined` (as input) and makes sure that `payload.oldPath` and `payload.path` (as output) are each the empty string `''` rather than `undefined` should do it?

**Review by sadick254 — APPROVED** [review]
